### ISSUE TITLE
Is there a way to always show the tab bar?

### ISSUE THREAD

**Issue by agguser** [orbitalquark/textadept#10]
This is useful, when the window's title bar is hidden, to show the file name and edit status.

**Comment by orbitalquark** [comment]
Not without recompiling Textadept to stop hiding the tab bar with only one buffer open. The titlebar contains the information you are looking for. It seems like a waste of vertical space to repeat the information.

**Comment by agguser** [comment]
Could you please make an option for it? Some people hide all windows' borders and title bars; some hide them when when maximizing.

**Comment by rgieseke** [comment]
As a workaround you could probably open an Untitled scratch buffer via hooking into the buffer-closed event. If there is only one buffer left, open a new Untitled one.

**Comment by orbitalquark** [comment]
I'll consider making this an option and get back to you when I have some time.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/textadept/commit/d807c2c2b005badbef80c45cc79d0f5ed5730ba9

Added a new `ui.SHOW_ALL_TABS` option for `ui.tabs` in addition to the existing true/false. This will show up in the next nightly build.
