### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by Vm900** [orbitalquark/textadept#101]
Hi,
I keep getting this error though:
make: *** No rule to make target 'scintilla/curses/ScintillaCurses.cxx', needed by 'ScintillaCurses.o'.  Stop.
Thanks

**Comment by orbitalquark** [comment]
Did you run `make deps`? That command pulls in scintilla and scinterm (which provides ScintillaCurses.cxx).

**Comment by Vm900** [comment]
Yes i did

**Comment by orbitalquark** [comment]
Okay, well the nightlies built last night, so there doesn't appear to be an issue with the build process. Try `make clean-deps`, `make deps`, and then `make`.
