### ISSUE TITLE
small issue in ta 11.2 beta2

### ISSUE THREAD

**Issue by gabdub** [orbitalquark/textadept#103]
When you type **"**, **'**, **[**, or **{** in an **_empty document_**, the closing character is added but the cursor remains in column 1.
If you select all the text and delete it and type one of those characters, the closing character is added, but both are selected and the cursor moves to column 3.

If you do the same with **_at least one character in the document_**, everything works fine (the closing character is added and the cursor remains in the center of both characters).

I think it worked fine on TA11.2 beta1.

**Comment by orbitalquark** [comment]
Thanks for the report. I will look into this.

**Comment by orbitalquark** [comment]
This should be fixed via https://github.com/orbitalquark/textadept/commit/fe7135350f64ba10a63626c6f363cc48a0679438 and will be in the next nightly build.

**Comment by gabdub** [comment]
works fine, thanks
