### ISSUE TITLE
TA11.2 beta3: tabs in empty documents

### ISSUE THREAD

**Issue by gabdub** [orbitalquark/textadept#109]
When I type multiple **tabs** in an **_empty document_**, the tabs/spaces are inserted but the cursor doesn't move or move only once.

**Comment by orbitalquark** [comment]
Thanks for the report. This is fixed via https://github.com/orbitalquark/textadept/commit/3ce1997b68b0454840870e35d84a4bb5feddfab3. I went ahead and updated the 11.2 beta 3 release archives with this fix.

**Comment by gabdub** [comment]
works fine, thanks!
