### ISSUE TITLE
Keyboard shortcuts break if the Command Entry is active and while active the Command Entry menu item is clicked

### ISSUE THREAD

**Issue by richbowen** [orbitalquark/textadept#127]
To reproduce, Activate Command Entry with Ctrl+E then click the "Command Entry" menu option from the Tools menu. Following that, all subsequent keyboard shortcuts should fail.

**Comment by orbitalquark** [comment]
Thanks for the report. I'll look into it when I have some time.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/textadept/commit/80816ecdba807af53f556dc3523b7726625bd5c4

This will be in tonight's nightly build.
