### ISSUE TITLE
textadept-curses - unsupported use of bold in theme

### ISSUE THREAD

**Issue by mrsean2k** [orbitalquark/textadept#131]
Depending on your terminal of choice, the default `term` scheme results in hidden text for fixtures such as line numbers, and syntax -dependent hidden comments etc.

This is particulary noticeable in _kitty_ and _alacritty_.

In _kitty_'s case in particular,  the author has taken a stance against the use of `bold` codes for text, rendering text that uses styles  such as:

`styles.number = {fore = colors.black, bold = true}`

as black on a black background, visible only when highlighted.

I haven't got a dog in the fight WRT what these terminals or textadept "should" do in this case - there's a world of pain in these things I don't understand properly - but I'd like to suggest a bold-safe version of `term.lua` as an option.

In my local copy, I've just defined `colors.gray = 0x808000` and then used `fore = colors.gray` everywhere `bold = true` would otherwise be used.

One thing that puzzles me is that most genuine gray variants such as `0x8C8C8C` seem to appear as a standard white. Is there some other restriction / approximation applied to these things even where a terminal is truecolor enabled?

**Comment by orbitalquark** [comment]
This is a terminal limitation. For the longest time terminals only supported 16 colors: 8 standard and 8 bold. Recently, some terminals support 256 colors, but the terminal platform of Textadept's editing component only supports 16. Any non-recognized color ends up being white. See https://orbitalquark.github.io/scinterm/#curses-compatibility

**Comment by mrsean2k** [comment]
Apologies, I should have found that, thanks for the pointer.

That solves all my particular problems - `colors.gray = 0x404040` is a good enough result for me. I don't know if there are enough people trying to use textadept-curses in an incompatible terminal to make a bold-safe version worth doing, but I'd be content if this was closed.

Thanks in general for textadept - it's an interesting exercise to see how much bloat I can remove from my development process.

**Comment by dispensable** [comment]
https://stackoverflow.com/a/63611791/6184420

Hi, After ncurse 6.1 seems like it can support more than 16 colors. Does this means we can add more colors to the term theme ?

@orbitalquark

**Comment by orbitalquark** [comment]
Scinterm (https://github.com/orbitalquark/scinterm) would need to add support for more than 16 colors first, then perhaps Textadept could make use of it.
