### ISSUE TITLE
Misleading information in readme

### ISSUE THREAD

**Issue by exebook** [orbitalquark/textadept#14]
Readme says "no external dependencies except GTK and ncurses" but the first thing the `make` does is downloading Scintilla.

So is this basically a scintilla based editor?

**Comment by orbitalquark** [comment]
Sorry for the confusion. In this case, external means no other system dependencies other than GTK and ncurses. Any other required dependencies are pulled and compiled in as necessary. I'll look into rewording the README.

Yes, Textadept is a Scintilla-based editor.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/textadept/commit/a211cd312ed68f5e89a4ec228983f17f1ab1fedf
