### ISSUE TITLE
11.3 beta 2: recent_files not as-recent-as-possible

### ISSUE THREAD

**Issue by metaleap** [orbitalquark/textadept#142]
Loving TextAdept! My new dev fav, gorgeously unbloated yet all(ua)-powerful. Noticed a quirk: as I close a file/tab, I'd expect it to then show up in `io.recent_files` and `io.open_recent_file()` but it doesn't. More like only 1 lonely file that I had open and closed in an earlier session. Files/tabs closed just-seconds-ago in the _current_ session don't make the list somehow...

Known issue or new bug?

(Setup: Void Linux x86_64, kernel 4.19.212_1) [init.lua](https://github.com/orbitalquark/textadept/files/7538807/init.lua.txt)

**Comment by orbitalquark** [comment]
The recent files list is added to on file open, not close. Also, session files have their own recent file lists that, on load, overwrite the current one.

**Comment by metaleap** [comment]
Ah that makes sense in some manner.. for my use-case ("reopen closed tab") I'll better just track close events I think. Thanks then!
