### ISSUE TITLE
11.3beta2: ui.dialogs.inputbox does not work as described 

### ISSUE THREAD

**Issue by metaleap** [orbitalquark/textadept#145]
Are the docs out of date or is it a new beta bug?

With this:

```lua
keys['ctrl+t'] = function()
    local bla = ui.dialogs.inputbox{informative_text = 'Bla:',  text = 'foo' }
    ui.print(bla)
end
```

I can enter anything I want, all that's printed is `1`. Or `_OK` if I set that `string_output`.

Or am I missing something? Linux version here.

**Comment by orbitalquark** [comment]
Example 6 is wrong. `ui.dialogs.inputbox()` returns button followed by input text. Thanks for catching this.

**Comment by metaleap** [comment]
> `ui.dialogs.inputbox()` returns button followed by input text

Not at my end was what I'm saying. Here I only get the button returned, essentially. The entered text is lost into the void afaict  =)

**Comment by manuelmontenegro** [comment]
> Not at my end was what I'm saying. Here I only get the button returned, essentially. The entered text is lost into the void afaict =)

As far I understand `inputbox` returns a pair with both things:

```lua
local button, text = ui.dialogs.inputbox{informative_text = 'Bla:',  text = 'foo' }
print(text)
```

**Comment by metaleap** [comment]
Oh neat, will check that out, thanks @manuelmontenegro. That's probably my issue. Wasn't fully tuned in to the Lua feature of "pairs" tbh. Looks then like Lua does not pass pairs fully as multiple args into "varargs funcs" like here `ui.print(...)`  =)

**Comment by metaleap** [comment]
That was it, thanks @manuelmontenegro. @orbitalquark feel free to close this Issue at any time!
