### ISSUE TITLE
How to horizontally scroll with Shift + Mouse wheel?

### ISSUE THREAD

**Issue by amitbha** [orbitalquark/textadept#159]
VSCode support horizontally scroll view with Shift + Mouse wheel.
The test code for textadept:
~~~
-- button: The mouse button number that was clicked
-- 1 (left button), 2 (middle button), 3 (right button), 4 (wheel up), or 5 (wheel down).
events.connect(events.MOUSE, function(msg)
    if msg.button == 4 and msg.shift then ui.print(msg.event) end
end)
~~~
But the function was never entered.

**Comment by snoopy** [comment]
Are you using the terminal version? The API says it only works with that:
>Emitted by the terminal version for an unhandled mouse event.

**Comment by amitbha** [comment]
My mistake.
Any other way to do this?

**Comment by orbitalquark** [comment]
Thanks for the suggestion. I've added this functionality to Scinterm, the terminal platform for Scintilla (Textadept's editing component).

https://github.com/orbitalquark/scinterm/commit/475d8d43f3418590c28bd2fb07ee9229d1fa2d07

It will be in the next nightly build.

**Comment by amitbha** [comment]
How about Textadept-gtk? 😀

**Comment by orbitalquark** [comment]
That would require an upstream patch to Scintilla. I'll consider submitting one when I have some time, but I'm not very familiar in that area.

**Comment by orbitalquark** [comment]
I've submitted an upstream patch[1] to the Scintilla mailing list for Shift+Mouse Wheel to be horizontal scroll. It's up to Neil if this will be default behavior for GTK applications. You can apply the patch manually and compile Textadept GTK with this behavior if you like.

[1]: https://groups.google.com/g/scintilla-interest/c/liR78w3UQLA

**Comment by gabdub** [comment]
This is really cool for me. I hope it gets added. This is very common behavior in graphics programs like GIMP, Inkscape and others.
However, what I noticed is that horizontal scrolling with this patch is very slow.
If you move the scrooll wheel over the horizontal scroll bar, the windows moves 12 characters at a time (at least on my machine), but over the buffer it moves only 1/3 of a character.

**Comment by orbitalquark** [comment]
Yes, I noticed that too. I have proposed a higher scaling factor for the patch. We'll see what happens.

**Comment by orbitalquark** [comment]
Neil accepted the patch for Scintilla. I've added it to Textadept[1] and it will be in tonight's nightly build.

[1]: https://github.com/orbitalquark/textadept/commit/48577534bb7f8b5ee510b4f38ae24a8d430ce3de
