### ISSUE TITLE
Textadept_11.3_beta_3: needless 'nul' character added to file end

### ISSUE THREAD

**Issue by amitbha** [orbitalquark/textadept#161]
System:  Manjaro 21.2
Textadept-gtk3: [11.3.beta.3](https://github.com/orbitalquark/textadept/releases/tag/textadept_11.3_beta_3)

After editing file, textadept 11.3b3 will automatically add a needless 'nul' character to the end of the file.
Open that file again, textadept will show a whole messy-code. Switch encodings doesn't help.
I open the file with scite, no messy-code, find out the ending 'nul', remove it, then everything back to normal.

Any possible to be more robust with mixed-encoding text?

**Comment by orbitalquark** [comment]
Thanks so much for the report. This has been fixed and the release binaries updated.

https://github.com/orbitalquark/textadept/commit/d54c43099bd71c37339dd03f487319222b335778
