### ISSUE TITLE
Error when hitting Tab

### ISSUE THREAD

**Issue by winks** [orbitalquark/textadept#164]
### Steps to reproduce

  * open a new buffer
  * type "./foo.xml"
  * hit the Tab key

  * It also occurs with a string ending in ".lua"
  * It does not occur with ".txt" or ".c"

### Expected

  * a "Tab" character after the text

### Result

In `[Message Buffer]`

```
bad argument #xml to '?' (string/nil expected, got table)

```

(or "#lua ...")

This is reproducible in 11.2 (Linux) and 11.1 (Linux), and also in 11.3 beta3

**Comment by gabdub** [comment]
Same here. TA 11.2 (win 10)
If I type any lexer name (ansi_c for example) and press TAB I got the error:
lua: ...textadept/modules/textadept\menu.lua:54: bad argument #ansi_c to 'insert' (string/nil expected, got table)

**Comment by orbitalquark** [comment]
Thanks for the report. Fixed via https://github.com/orbitalquark/textadept/commit/0f9d6f917173b1a22559fc42d12bbfc9bf4e783c

This will be in the next nightly build.

**Comment by winks** [comment]
Thanks for the quick response, unfortunately it only fixes the error, now it won't input a TAB character after "xml" or "lua"

**Comment by orbitalquark** [comment]
You're right. Sorry about that. Fixed via https://github.com/orbitalquark/textadept/commit/9a91848fc752a364f16724f564288bcc20d6a63a

**Comment by winks** [comment]
That did the trick, thanks a lot for TextAdept!
