### ISSUE TITLE
UI bug after zooming

### ISSUE THREAD

**Issue by mierenhoop** [orbitalquark/textadept#165]
When zooming in and zooming out again, the numbers column permanently moves to the right with more padding. Reset zoom does not help.
Before:
![Screenshot 2021-12-29 004324](https://user-images.githubusercontent.com/46939409/147615116-bfe90759-1e37-43a6-bc12-ac016d7bd7bc.png)
After:
![Screenshot 2021-12-29 004252](https://user-images.githubusercontent.com/46939409/147615128-6a0b3b65-bc99-4be6-96bd-1c968305ff3a.png)

This occurs on both Windows, and Linux, version 11.2 and nightly.

**Comment by orbitalquark** [comment]
Thanks for the report. Fixed via https://github.com/orbitalquark/textadept/commit/f4d8b6036ef7e631ee87ae5f89709fb798818fea
