### ISSUE TITLE
Hotkeys such as Ctrl-S and Ctrl-N do not work in non-latin keyboard layouts.

### ISSUE THREAD

**Issue by Sturwandan** [orbitalquark/textadept#169]
Normally, all keyboard shortcuts are layout-agnostic, such as Ctrl-S would work even if the current layout is Cyrillic and you are actually hitting Ctrl-Ы since Ы is printed on same key as S, and same goes to all other keypresses, they do the same things, independent from the current keyboard layout. However in the current state of affairs, I have to switch the layout to latin before hitting Ctrl-S in order to save file, otherwise the keypress would do nothing.

Tested on Xfce + X11 + glibc + x86_64 Linux 5.15. Textadept is latest master cloned today, last commit 2022 jan 13, 9fcb8de0ed557f6d378861d8b07969132c31f1e3. 

The bug existed in older versions, but I didn't report it before because I thought that it could have been already fixed.

**Comment by orbitalquark** [comment]
Unlike other editors, when it comes to key bindings Textadept uses the actual key that would be typed, along with any modifiers pressed. Unfortunately, for non-Latin layouts this means you will have to define key bindings with non-Latin characters. Therefore you will have to adapt Textadept's *modules/textadept/keys.lua* with Cyrillic characters. Sorry for the inconvenience :(

**Comment by rgieseke** [comment]
Maybe the solution discussed here works for you too: https://github.com/orbitalquark/textadept/issues/64

**Comment by Sturwandan** [comment]
I have changed some lines, but the keypresses didn't work still:
```
  [buffer.new] = {{'ctrl+n', 'ctrl+т'}, 'cmd+n', 'ctrl+meta+n'},
  [io.open_file] = {{'ctrl+o', 'ctrl+щ'}, 'cmd+o', 'ctrl+o'},
  [buffer.save] = {{'ctrl+s', 'ctrl+ы'}, 'cmd+s', 'ctrl+s'},
```

**PS:** Oops, my bug report is a duplicate, seems. Sorry.

@rgieseke,
Though, the code from the page worked, thanks.

**Comment by rgieseke** [comment]
This has come up lots of times and i'm not sure if there is a 'perfectly simple' solution yet.

See also this by @al-zatv: https://github.com/al-zatv/textadept_init/blob/master/init_v11.lua#L6

I don't know whether this stopped working with 11.1 as it was commented out then apparently.

**Comment by al-zatv** [comment]
It's my config, and it is working in terminal version of text-adept.
Probably, that's why I comment that code out -- but not remember exactly.
GUI version is NOT working (but I usually use terminal version mostly, so I
notice it a minute ago)

**Comment by al-zatv** [comment]
To be clear:
- it is my actual config, so code is commented out
- in Russian mode
-- in console version, if I press smth like Ctrl+Ы (which is Ctrl+S) it is
working as it should
-- in GUI, it is not working.

**Comment by Sturwandan** [comment]
Anyway, since it's a duplicate of #64 then I suggest, to either close it, if you don't have any plans to fix in default install, even though textadept could read keyboard layout list and compile list of aliases automatically, or leave it's open until it is fixed.

My particular case is solved with this code:
_Originally posted by @winterwolf in https://github.com/orbitalquark/textadept/issues/64#issuecomment-785710403_

**Comment by orbitalquark** [comment]
I'm going to close this because I do not know how to read a keyboard layout list and compile a list of aliases automatically. I regrettably do not use an international keyboard layout and could not effectively test a solution either.
