### ISSUE TITLE
Text Adept does not allow the user to drag tabs around

### ISSUE THREAD

**Issue by Sturwandan** [orbitalquark/textadept#170]
I wanted to put related tabs next to each other, but unlike most other multi-tab applications, drag and drop does not work for textadept tabs.

I have tried to open ~/.textadept/session but it turns out to be unreadable.

**Comment by rgieseke** [comment]
Check out this as a potential workaround: https://github.com/CertHaramas/TextAdept.TabBarMan

(Not sure if it works unmodified, as it's three years old apparently.)

**Comment by orbitalquark** [comment]
Unfortunately, Textadept does not support this feature yet. It's been on my TODO list for a while. Originally, Textadept did not have tabs. They were added later.

**Comment by Sturwandan** [comment]
@rgieseke thanks. It kinda works, though it's quite uncomfortable to use.

**Comment by gabdub** [comment]
I implemented tab reordering in **tatoolbar**, if you don't mind the many other things I put there.
see:  https://github.com/gabdub/ta-tweaks/wiki/tatoolbar---tabs-&-theming
But it may be a little "too much" ;-)

**Comment by orbitalquark** [comment]
Textadept now supports rearrangeable tabs and has a `move_buffer()` function for rearranging tabs via Lua: https://github.com/orbitalquark/textadept/commit/092d5984e16f2d8f844dc88a417ed6f9defdf42c

This will be in tomorrow's nightly build. It did not make it into tonight's build unfortunately.
