### ISSUE TITLE
Menubar is gone.

### ISSUE THREAD

**Issue by amitbha** [orbitalquark/textadept#172]
I don't know what happened. The menubar disappeared. 
What I've done before is updating picom-git. Does it matter? or a gtk3 problem?
Back to the default config file, the problem still exist.

![0211-224604](https://user-images.githubusercontent.com/4060625/153613188-40f6076b-59fd-4098-b440-6cf9a73ed168.png)

**Comment by orbitalquark** [comment]
What platform are you on, and what version of Textadept? Check and see if any Lua scripts are running 'textadept.menu.menubar = nil'.

You can try to get it back by entering this into the command entry:

  textadept.menu.menubar = textadept.menu.menubar

If you are on Linux, you can test with a completely empty config by running in your terminal:

  textadept -f -u /tmp

Some Linux distros like to move an application's menubar from the window to the top of the screen like on macOS. See if your other applications have a menubar.

**Comment by amitbha** [comment]
I know what's happened.
The package `gtk3-libwinmenu` is updated, which auto-hides the menubar. 
Press right-ctrl to show the menubar.
Everything is ok.
