### ISSUE TITLE
API: ui.print() lead to buffer change.

### ISSUE THREAD

**Issue by amitbha** [orbitalquark/textadept#173]
[Textadept](https://github.com/orbitalquark/textadept)-gtk3 v11.3
Manjaro 21.2.3

~~~lua
-- Process lines from the current file, then output to message buffer
count = buffer.line_count
for i = 1, count do
    line = buffer.get_line(i)
    -- do something
    ui.print(line)
end
~~~
The output is a mess.
Because while invoke ui.print(), the current buffer will switch to the message buffer.

Expected: ui.print() don't change the current buffer or support print to message buffer safely.

**Comment by snoopy** [comment]
Have you tried `ui.silent_print = true`?
https://orbitalquark.github.io/textadept/api.html#ui

If that doesn't work you could dump your output into a table and then print the table when you're done.

**Comment by amitbha** [comment]
@snoopy Thx. It works. I didn't read document carefully.

**Comment by amitbha** [comment]
Update: 
It works sometimes. But now does not function. It's weird and unreliable.
I have to use table to cache result for print.

**Comment by orbitalquark** [comment]
If you want to use `ui.silent_print = true`, you need to call it before each and every `ui.print()` call you make, not outside the loop. As the documentation says, the flag is not guaranteed to remain constant.

**Comment by amitbha** [comment]
Got it. Maybe I can wrap them together into a function for print.
But a print cache is more flexible.
