### ISSUE TITLE
Find Next, Find Prev do not work for 0 length regex searches

### ISSUE THREAD

**Issue by jk411** [orbitalquark/textadept#174]
Try to search for (regex): ^ or $
Find Next and Find Prev get stuck on first hit.
Replace all works.
These searches are 0 in length, if matched,
maybe that's causing problems.

Textadept 11.3 compiled from sources
on Alpine Linux and termux

**Comment by orbitalquark** [comment]
I think this is related to the part of the discussion in #86 from last October.
