### ISSUE TITLE
[Enhancement] Support Android (AOSP).

### ISSUE THREAD

**Issue by RokeJulianLockhart** [orbitalquark/textadept#192]
This would be the first text editor for AOSP that exposes a CLI, TUI, and GUI.

**Comment by orbitalquark** [comment]
No, sorry. I am not aware of a GTK distribution for Android (GTK is the cross-platform GUI toolkit Textadept uses), I don't think the terminal version would be very useful on Android, and I do not have an Android device to test on.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/orbitalquark/textadept/issues/192#issuecomment-1079999529

@orbitalquark, actually, the TUI that is provided to the terminal is very useful, because it is usable via [`termux/termux-app`](https://github.com/termux/termux-app), which is a terminal as much as any alternative, not least because it is able to interface with the OS as much as you expect from any terminal.

You should be able to evaluate how much textadept currently supports AOSP without hardware that supports it, if you utilise [`genymotion.co`](https://genymotion.com) (via VirtualBox or the internet), or compile AOSP for your architecture. [`android-x86.org/source.html`](https://android-x86.org/source.html) improves the ease of the 2nd option.

Additionally, although I am not significantly interested in support for the GUI of TA natively for AOSP, GTK4 is able to support Android (albeit rudimentarily), without significant effort, if [`docs.gtk.org/gtk4/broadway.html`](https://docs.gtk.org/gtk4/broadway.html) is utilised. I believe this would actually allow the GUI to support approximately every OS that includes an internet browser.

**Comment by orbitalquark** [comment]
Thanks for the info. I don't have the time or desire to do this, but if you or someone wants to give it a go and submit patches, feel free to do so. It's more than just compiling and testing in an emulator/virtual device. I have to worry about distribution and support, especially if there's another necessary layer (Termux).

**Comment by RokeJulianLockhart** [comment]
> I have to worry about distribution and support, especially if there's another necessary layer (Termux).

@orbitalquark, usually I would say that a terminal emulator is a standard requirement for a TUI, but Termux is in a precarious position due to API lockdown.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/orbitalquark/textadept/issues/192#event-6314114480

@orbitalquark, this should probably be re-closed as "unplanned" (rather than "completed"), since GitHub has improved since it was last closed, by now providing closure reasons.
