### ISSUE TITLE
Suggestion for expanding the file encoding format of CP936

### ISSUE THREAD

**Issue by yanecc** [orbitalquark/textadept#196]
Whether could textadept add IO support for the encoding format of CP936 so that the software can smoothly handle more Asian languages rather than show messy code?
Or How could users add support for more encoding formats themselves?

**Comment by orbitalquark** [comment]
Does this help? https://orbitalquark.github.io/textadept/manual.html#encoding

**Comment by yanecc** [comment]
That's it!
