### ISSUE TITLE
[Enhancement] "Edit" > "Preferences" does not look like it's been invoked, when selected.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [orbitalquark/textadept#200]
#### Issue

Clicking the item of the relevant context-menu:

![Image](https://github.com/user-attachments/assets/fb6e0104-7569-4581-898b-40614579c96f)

...does nothing.

#### Environment

1. #### Application

   [`12.6.linux`](https://github.com/orbitalquark/textadept/releases/download/textadept_12.6/textadept_12.6.linux.tgz)

1. #### OS & DE

   1. ~~~sh
      #!/usr/bin/env sh
      kinfo
      ~~~

   1. > ~~~YAML
      > Operating System: Fedora Linux 41
      > KDE Plasma Version: 6.2.5
      > KDE Frameworks Version: 6.10.0
      > Qt Version: 6.8.1
      > Kernel Version: 6.12.11-200.fc41.x86_64 (64-bit)
      > Graphics Platform: Wayland
      > ~~~

**Comment by orbitalquark** [comment]
If you are referring to the Edit > Preferences menu item, it simply opens your *~/.textadept/init.lua* file, which by default is empty. The titlebar should indicate this file is open, but otherwise it does indeed look like nothing happens if your preferences file is empty.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/orbitalquark/textadept/issues/200#issuecomment-1126974293

@orbitalquark, maybe if you included a shebang (`#!/usr/bin/env lua`) at the start of the file, it would be more obvious.

**Comment by rgieseke** [comment]
> @orbitalquark, maybe if you included a shebang (#!/usr/bin/env lua) at the start of the file, it would be more obvious.

It's not really an executable file which is invoked with a Lua interpreter, a comment string with a link to the preferences docs or some commented out examples what to put there might be helpful though.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/orbitalquark/textadept/issues/200#issuecomment-2629015454

@rgieseke, if it is a Lua file, having a shebang can help the OS determine what kind of text file it is, regardless. If safety is a consideration, I presume the execution bits are already unset?

**Comment by rgieseke** [comment]
> @rgieseke, if it is a Lua file, having a shebang can help the OS determine what kind of text file it is, regardless. If safety is a consideration, I presume the execution bits are already unset?

For that it has the file extension I think, having an unused shebang could be as confusing as en empty file.
