### ISSUE TITLE
Run command doesnt work after compiling  my help.cpp file on macOS

### ISSUE THREAD

**Issue by amay5267** [orbitalquark/textadept#201]
[Message Buffer]
   1  > cd /Users/usr/Desktop
   2  > ./"help"
   3  Failed to execute child process "./"help"" (No such file or directory)
   4  > exit status: 256
   5

however it should execute child process ./help

there are some unneeded quotation marks i think blocking actual execution.

i am not expert in lua so i cannot patch it myself

Can you please patch 

textadept/modules/textadept/run.lua

at line 255 ?

and replace 

cpp= './“%e”',

with something like 

cpp=OSX './%e', without quotation marks

**Comment by orbitalquark** [comment]
Thanks for the report. Fixed via https://github.com/orbitalquark/textadept/commit/1798c6a842978a05396b39427fdda148bec08899

Use `"./%e"` instead of `./"%e"`.
