### ISSUE TITLE
Request: duplicate selection with ctrl-d when selection is active

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#206]
Ctrl-d duplicates the line and that is cool. Is there any way to duplicate the selection when it is active?

**Comment by orbitalquark** [comment]
There is `buffer:selection_duplicate()`[1]. That sounds like what you're looking for.

[1]: https://orbitalquark.github.io/textadept/api.html#buffer.selection_duplicate

**Comment by paaguti** [comment]
Cool thanks :-) 
The documentation is somehow misleading. It duplicates a *rectangular selection* on the right or a multiple-line selection below.
I was confused there...

So I'm using this in my init.lua and it is a time saver ;-)
```
--
-- Better duplicate region
keys['ctrl+d'] = buffer.selection_duplicate
textadept.menu.menubar[_L['Edit']][_L['Duplicate Line']][2] = buffer.selection_duplicate
textadept.menu.menubar[_L['Edit']][_L['Duplicate Line']][1] = 'Duplicate'

```

**Comment by orbitalquark** [comment]
I have updated the documentation to reflect the behavior concerning multiple lines: https://github.com/orbitalquark/textadept/commit/39f9f4f39b30ef3f9a31219d81a6070511eede2e

**Comment by paaguti** [comment]
IMHO the 'end of the selection' may be confusing for beginners, especially for rectangular regions... Maybe the 'at the right' part should be mentioned somehow...

**Comment by orbitalquark** [comment]
Closing in favor of #208, where a decision on this will be made.
