### ISSUE TITLE
Code folding for R language?

### ISSUE THREAD

**Issue by hckiang** [orbitalquark/textadept#207]
Code folding doesn't seem to be working in R. I am wondering how difficult will it be for me to implement it myself? Should I write a new module that works on top of the rstats language module? Or do I need to modify the original lexer? (I can't find the lexer in ta's source code...)

**Comment by rgieseke** [comment]
The sources for the lexers are in the Scintillua project: https://github.com/orbitalquark/scintillua/blob/default/lexers/rstats.lua

**Comment by rgieseke** [comment]
There are no folding rules defined there, so most likely you could add something from the lexer of a similarly structured language.

**Comment by hckiang** [comment]
Thanks for pointing me there! I've sorted it out.

**Comment by rgieseke** [comment]
Feel free to share here or create an issue in the Scintillua repo, i'm sure @orbitalquark is happy to include the folding code in the default lexer.

**Comment by rgieseke** [comment]
Ha, you already did (https://github.com/orbitalquark/scintillua/pull/63)! :smiley:
