### ISSUE TITLE
Two small issues with file_types mapping

### ISSUE THREAD

**Issue by pkulchenko** [orbitalquark/textadept#21]
I noticed a couple of small issues with the mapping in default/modules/textadept/file_types.lua#L26:

1. extension p8 references "pico" lexer, but it doesn't exist; it needs to be pico8
2. fs extension references both "fsharp" and "forth" lexers

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/textadept/commit/cfc696571b49fa0728b19a32671cc6f651181611
