### ISSUE TITLE
typo in `manual.md`?

### ISSUE THREAD

**Issue by ousia** [orbitalquark/textadept#214]
@orbitalquark,

I guess the following

https://github.com/orbitalquark/textadept/blob/c1c4fd1f7b6a37ac7a4ffb60f725231daf0505cf/docs/manual.md#L122

should read

``` lua
textadept.editing.strip_trailing_spaces = true
```

**Comment by orbitalquark** [comment]
Indeed, thanks. Fixed via https://github.com/orbitalquark/textadept/commit/cfcc39836cf46ca2d418b59ad1a7122169ae9128

**Comment by ousia** [comment]
Many thanks for your fix and your excellent work with Textadept, @orbitalquark.
