### ISSUE TITLE
Map context menu key

### ISSUE THREAD

**Issue by mhwombat** [orbitalquark/textadept#220]
Is there a way to have the "menu" ("context menu") key launch the context (right click) menu, as it does in many apps?

I don't see any mention of this key, or how to map a key to launch a menu, in the Quick Reference manual or the API docs. I had a look at the code in the textadept repo too, but I couldn't figure out how to do this.

 BTW, I bought the Quick Reference manual today. It's very well-written!

**Comment by orbitalquark** [comment]
I have just committed https://github.com/orbitalquark/textadept/commit/85ef06aaeb4c3cbfb9dc250985844945aff7a7f8 to address this. The next nightly build will have a new `ui.popup_menu()` function for displaying popup menus. The "menu" key, as well as "shift+f10", will display the default right-click context menu.

Thanks for the suggestion!

**Comment by mhwombat** [comment]
Works perfectly! Thank you so much for this feature.
