### ISSUE TITLE
[11.4 beta] `keys.f8` doesn’t work on WIN32

### ISSUE THREAD

**Issue by ousia** [orbitalquark/textadept#222]
As reported in #212, I had to add to get the backslash car in a Spanish keyboard using Windows:

``` lua
keys['ctrl+alt+\\'] = nil -- disable problematic shortcut
```

Now I’m experiencing a weird issue, I cannot get this working (only on Windows):

``` lua
keys.f8 = textadept.run.run
```

For some strange reason `keys.f8` seems to be not available in Windows.

It works perfectly fine with any other key, such as in:

``` lua
keys.f7 = textadept.run.run
```

Is there any reason because `keys.f8` seems not to be available for shortcuts in Windows?

Many thanks for your help.

**Comment by orbitalquark** [comment]
I was able to use the command entry to set `keys.f8 = function() ui.print('hi') end` and when I pressed F8 I got 'hi' printed in the Message Buffer.

Pressing F8 by itself seems to move focus out of the buffer on Windows and Linux. I'm not sure why this is (perhaps it's a GTK thing), but binding F8 to a Lua function seems to work fine for me.

**Comment by ousia** [comment]
I have to test that on Windows (I’m on Linux now).

**Comment by ousia** [comment]
> I was able to use the command entry to set `keys.f8 = function() ui.print('hi') end` and when I pressed F8 I got 'hi' printed in the Message Buffer.

For some strange reason, the Windows machine I have access to doesn’t even get `keys.f8 = function() ui.print('hi') end`.

> Pressing F8 by itself seems to move focus out of the buffer on Windows and Linux. I'm not sure why this is (perhaps it's a GTK thing), but binding F8 to a Lua function seems to work fine for me.

I’m not sure I’m getting it. This is something that also happens with version 11.3 in Linux.

 If I add `keys.f7 = function() ui.print('hi') end`, the message buffer is displayed (even if `init.lua` includes `textadept.run.run_in_background = true`).

Just in case it might help.

**Comment by ousia** [comment]
For some strange reason, `F8` seems to be not available on the _Windows_ system I use. `ctrl+r` works just fine.

Since it may be an issue with the computer I use, I’m closing the issue myself.

**Comment by orbitalquark** [comment]
`textadept.run.run_in_background` only affects `textadept.run.run()`. It does not affect `ui.print()` calls.

On your Windows box you can modify *core/keys.lua* around line 180 from

  -- if CURSES then ui.statusbar_text = string.format('"%s"', key_seq) end

to

  ui.statusbar_text = string.format('"%s"', key_seq)

After restarting Textadept, every key you press will be printed to the statusbar. Maybe that will help shed some light on the issue you're experiencing.
