### ISSUE TITLE
key chains with hydra-like functionality

### ISSUE THREAD

**Issue by mhwombat** [orbitalquark/textadept#224]
I'm working on writing a textadept plug-in like the emacs "hydra" plugin. Similar plugins are also available for neovim and some other editors. While looking into how I would implement it, I realised that the key chain functionality provides most of what I'm looking for. So I wanted to co-ordinate with you to see if you are interested in adding any of this to textadept, or if I should focus developing a separate plugin.

As I see it, the key chain functionality could be fully hydra-like with two added features. The first one is the most important.

1. When a key chain is activated, the status bar (or a pop-up) could display the possible next keys and their actions. Better yet, when defining a key chain, the user could specify some text describing the action that would be displayed instead of the action itself, e.g. "open file" instead of io.open_file".

2. It would also be nice if there was a way to say that an action doesn't end the key chain. For example, suppose I trigger a key chain for "word mode". I would have the right arrow select the next word, the left arrow select the previous word, and "d" delete the word. But I would want to keep the chain active so that I can type "wwwd" to move forward three words and then delete that word. Any other key, or escape, would end the chain.

The advantage of this approach is that the user seldom needs the mouse, and never needs to memorise key sequences. I'd appreciate any thoughts you have on this.

**Comment by orbitalquark** [comment]
I think Textadept could benefit from something like this, but I would have to see a sample implementation of what the end-result might look like. I recommend you develop a plugin and if it looks like core Textadept would benefit from it, I can incorporate it. This has been done in the past like with recordable macros.
