### ISSUE TITLE
preferences won't open

### ISSUE THREAD

**Issue by Carandiru0** [orbitalquark/textadept#230]
I'm not sure why, when I click on Preferences, nothing comes up - no window/dialog - just nothing.
How to resolve this?
Tried 11.3 and 11.4 beta + nightly all have the same result. Windows 10 Pro N.

**Comment by orbitalquark** [comment]
Duplicate of #35.

https://github.com/orbitalquark/textadept/discussions/35#discussioncomment-299508

**Comment by orbitalquark** [comment]
Duplicate of #35.

https://github.com/orbitalquark/textadept/discussions/35#discussioncomment-299508
