### ISSUE TITLE
options in `init.lua` for session loading

### ISSUE THREAD

**Issue by ousia** [orbitalquark/textadept#238]
> [This comes from #228.]

@orbitalquark,

this is a proposal to have options of session loading in `init.lua` for:

* `-s` last (or another) session loading.
* `-n`no state saving and restoring.
* `-f` force unique instance.

I don’t know which the names should be, but the functionality is needed in Textadept (and it shouldn’t be complex or hard to get).

Many thanks for your help.

**Comment by orbitalquark** [comment]
1. To disable sessions from *~/.textadept/init.lua*, use this:

  textadept.session.save_on_quit = false

That also disables session loading on startup.

2. To load a custom session on startup from *~/.textadept/init.lua*, use this:

  events.connect(events.INITIALIZED, function()
    textadept.session.load('/path/to/custom_session')
  end)

3. There is no way to force a unique instance from *~/.textadept/init.lua*. The code for determining that happens before Lua is initialized.

**Comment by ousia** [comment]
@orbitalquark,

many thanks for your help.

I’m using version 11.3 in Linux (Fedora 35 if that matters) and I’m afraid I cannot make none of them work when opening the file with the right-click menu (or by linking the file extension with the program).

Since I use Windows too, my code reads (copied from https://github.com/orbitalquark/textadept/wiki/import-default-session):

``` lua
events.connect(events.INITIALIZED, function()
  textadept.session.load(_USERHOME..'/session')
end)
```

What am I doing wrong here?

Many thanks for your help.

**Comment by orbitalquark** [comment]
I'm going to venture a guess that when you open a file with Textadept via your file manager's "Open With..." option, it calls Textadept like this:

  textadept file.ext

When that happens, Textadept opens your file as requested, but your `events.INITIALIZED` handler's call to `textadept.session.load()` immediately closes that file and loads the default session.

You can try one of the following:

1. Change your file manager's method for launching Textadept to something like:

  textadept -s session file.ext

2. Copy the `import_default_session()` function https://github.com/orbitalquark/textadept/wiki/import-default-session and use:

  events.connect(events.INITIALIZED, function()
    import_default_session()
  end)

**Comment by ousia** [comment]
> I'm going to venture a guess that when you open a file with Textadept via your file manager's "Open With..." option, it calls Textadept like this: 
> 
> ```
> textadept file.ext
> ```
> 
>  When that happens, Textadept opens your file as requested, but your `events.INITIALIZED` handler's call to `textadept.session.load()` immediately closes that file and loads the default session.

Many thanks for your reply, @orbitalquark.

Sorry for not explaining what I couldn’t make it work.

File loads fine, but the session isn’t imported when I use the right–click (or double–click by file association).

If I type in a command line: `textadept file.ext`, both the file is opened and previous session is imported.
 
> You can try one of the following:
>
> 1. Change your file manager's method for launching Textadept to something like:
> 
>     ```
>     textadept -s session file.ext
>     ```

I don’t know how to achieve that.

And I’d rather also avoid solutions that won’t work outside `init.lua`.

> 2. Copy the `import_default_session()` function https://github.com/orbitalquark/textadept/wiki/import-default-session and use:
> 
> ```
> events.connect(events.INITIALIZED, function()
>   import_default_session()
>  end)
> ```

Not working, same reasons as above.

I don’t know what may be wrong here.

Many thanks for your help.

**Comment by ousia** [comment]
I have discovered what was wrong here (although it makes no sense to me).

As suggested in https://github.com/orbitalquark/textadept/discussions/228#discussioncomment-3139669, I replaced the value in the `Exec` key `textadept.desktop` from `textadept` to `textadept -s -f`.

That didn’t work when using double– or right–click to open the file. It also prevented both suggestions in https://github.com/orbitalquark/textadept/issues/238#issuecomment-1186221646 to work.

As I removed the options from `textadep.desktop` (only `textadept` is used now), `textadept.session.load(_USERHOME..'/session')` didn’t work. But `import_default_session()` works fine now.

As a final comment, I’m not sure Textadept is behaving as it is supposed to do (or at least, I would expect a different response from `textadept -s -f`).

But I may be well missing the whole point with the `-s -f` options.

Many thanks for your help again.

**Comment by orbitalquark** [comment]
The `-s` option requires the name of a session to load, so you'd have to put something like `textadept -s custom -f` in your *textadept.desktop* file to load something other than the default session.

`textadept.session.load(_USERHOME..'/session')` is completely unnecessary, as this is the default behavior. ('session' is the default session file name.)

I am unsure if there is a problem here, or if it is a configuration error.

**Comment by jmario74** [comment]
don't really understand the discussion completely so i will just show something similar that i have done that works for me on Ubuntu 20.04 with Textadept latest version portable. 
inside preferences:
```
local function import_default_session()
	textadept.session.load(_USERHOME..'/session')
	for i = 1, #arg do
		local filename = lfs.abspath(arg[i], arg[-1])
		if lfs.attributes(filename) then -- not a switch
			io.open_file(filename)
		end
	end
end
events.connect(events.VIEW_NEW,import_default_session)
```

**Comment by ousia** [comment]
> The `-s` option requires the name of a session to load, so you'd have to put something like `textadept -s custom -f` in your *textadept.desktop* file to load something other than the default session.

Sorry, I thought I read somewhere that `-s` imported the previous version by default.

> `textadept.session.load(_USERHOME..'/session')` is completely unnecessary, as this is the default behavior. ('session' is the default session file name.) I am unsure if there is a problem here, or if it is a configuration error.

Not when you are opening a file with the console (such as in `textadept another-file.txt`), the default is not to import previous session.

But in that case (as you ventured in https://github.com/orbitalquark/textadept/issues/238#issuecomment-1186221646), the new file won’t be opened (only the ones from the previous versions will be opened).

So I guess everything was a misconfiguration on my side.

Closing the issue myself.

**Comment by ousia** [comment]
> don't really understand the discussion completely so i will just show something similar that i have done that works for me on Ubuntu 20.04 with Textadept latest version portable.
> inside preferences:

I also confirmed this in https://github.com/orbitalquark/textadept/issues/238#issuecomment-1186257489.
