### ISSUE TITLE
HTML local documentation no longer generated

### ISSUE THREAD

**Issue by manuelmontenegro** [orbitalquark/textadept#240]
Since 11.4 alpha, the HTML files of the `docs` folder are no longer present in released files (except `index.html`). Only the Markdown files are there.

As a consequence, the menu options *Show Manual* and *Show Luadoc* silently fail.

Is there any `make` rule to generate those files?

Thanks,
Manuel.

**Comment by orbitalquark** [comment]
Oops, sorry about that :( Thanks for reporting this. Fixed via https://github.com/orbitalquark/textadept/commit/894b59328b8b7dd899c4d5be2e0c80f38f32ba3c

`make docs` will generate those files for you.
