### ISSUE TITLE
events.LEXER_LOADED not triggered when creating new file with Ctrl-N

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#244]
When I create a new buffer with 'ctrl+n', I don't see `events.LEXER_LOADED` triggered. 
I think it should, in order to detect that the new buffer is in text mode (AFAIK it is) and apply customisations.

**Comment by orbitalquark** [comment]
You are correct. Fixed via https://github.com/orbitalquark/textadept/commit/5371b727e63ee96ee4c6c1a77e3bcbe999749c70

Thanks for the report!
