### ISSUE TITLE
Chinese/Mandarin words not showing well

### ISSUE THREAD

**Issue by zhaolinlau** [orbitalquark/textadept#248]
![image](https://user-images.githubusercontent.com/68846168/183088837-72fad513-8e6c-4a05-948b-822963a26c57.png)

**Comment by orbitalquark** [comment]
Please try a different font. The default font for Windows probably does not support those characters.

**Comment by zhaolinlau** [comment]
> Please try a different font. The default font for Windows probably does not support those characters.

I tried to change to the Monospace font and it works, thank you <3.
