### ISSUE TITLE
Don't work keys command entry ctrl+e in textadept-curses

### ISSUE THREAD

**Issue by 9Demien9** [orbitalquark/textadept#251]
Hello! 
Don't work keys command entry ctrl+e in textadept-curses, switching buffers ctrl+tab, ctrl+b and more...
It works fine ctrl+r, ctrl+o...
Tested on two systems Debian 11 and Archlinux, DE I3wm (in Debian, I tested the additional ones on KDE Plasma).
The graphical application works fine, all keyboard shortcuts work as they should.
Please tell me what this could be related to?
Version: 11.4

**Comment by rgieseke** [comment]
Maybe it's the terminal emulator which is not passing through `ctr+e`? Is it the same emulator on all systems?

**Comment by 9Demien9** [comment]
Tested in two emulate terminal: konsole and xterm, and bare console.

**Comment by orbitalquark** [comment]
You can try uncommenting this line in *core/keys.lua* to print keys to the statusbar and see if Textadept is at least receiving them:

https://github.com/orbitalquark/textadept/blob/3d1edd40f90ad2a41d099bd877be0faa2538b649/core/keys.lua#L180

**Comment by 9Demien9** [comment]
> Вы можете попробовать раскомментировать эту строку в *core/keys.lua*, чтобы вывести ключи в строку состояния и посмотреть, получает ли их Textadept: [https://github.com/orbitalquark/textadept/blob/3d1edd40f90ad2a41d099bd877be0faa2538b649/core/keys. Луа#L180](https://github.com/orbitalquark/textadept/blob/3d1edd40f90ad2a41d099bd877be0faa2538b649/core/keys.lua#L180)

Yes, the keys in the status bar are displayed.
ctrl+e displayed, but there is a move to the end of the line, like the end key.
ctrl+tab displayed as shift+ , there is a movement through one character back.
ctrl+b displayed, there is a movement backwards character by character.

**Comment by orbitalquark** [comment]
The terminal version has a separate set of key bindings: https://orbitalquark.github.io/textadept/api.html#textadept.keys

ctrl+e: line end and ctrl+b: character back are expected results.

ctrl+tab probably is probably not recognized by any terminal. (A very limited number of non-alphabetic keys work with ctrl).
