### ISSUE TITLE
Spellcheck module - wrong en_US.aff file

### ISSUE THREAD

**Issue by uwdk** [orbitalquark/textadept#255]
It looks like the en_US.aff file within the Spellcheck module is incorrect (for 11.4 and nightly zip files) and potentially identical to the en_US.dic file.

11.4 beta modules appears to have the correct en_US.aff file:
https://github.com/orbitalquark/textadept/releases/download/textadept_11.4_beta/textadept_11.4_beta.modules.zip

**Comment by orbitalquark** [comment]
Thanks for the report. This should be fixed via https://github.com/orbitalquark/textadept-spellcheck/commit/d8a85e9bf380fc2f14f6b278f07089156c670316. When that build completes, you can get the correct files from the new zip, or you can keep the ones from 11.4 beta.
