### ISSUE TITLE
textadept.menu.select_command() "Run Command" dialog shows incorrect keybindings for some entries

### ISSUE THREAD

**Issue by richbowen** [orbitalquark/textadept#256]
For a number of menu options such as:
- Quickly Open Current Directory, `Shift+Ctrl+Alt+O`
- Quickly Open Current Project, `Shift+Ctrl+Alt+P`
- Previous Error, `Shift+Ctrl+Alt+E`
- Previous Buffer, `Shift+Ctrl+Tab`

Incorrect keybindings are displayed in the "Run Command" dialog spawned by the `select_command()` function:
- Quickly Open Current Directory, `Ctrl+Alt+O`
- Quickly Open Current Project, `Ctrl+Alt+P`
- Previous Error, `Ctrl+Alt+E`
- Previous Buffer, `Shift+Ctrl+`

![textadept-incorrect-keybindings-run-command-dialog](https://user-images.githubusercontent.com/5672238/187616624-88023445-9bdb-435e-a12d-9100b96d3b74.png)

**Comment by orbitalquark** [comment]
By design, Textadept uses and prints case-sensitive key bindings (the key itself, not the modifiers), so 'ctrl+alt+o' and 'ctrl+alt+O' are two different bindings.
