### ISSUE TITLE
Textadept 11.4 not compiling from a fresh git clone

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#257]
Hi,
I've tried to compile 11.4 on a Debian:latest and on a ubuntu:focal container and in both cases I get the following compilation error:
```
textadept.c: In function 'main':
textadept.c:2617:22: error: too few arguments to function 'scintilla_send_mouse'
 2617 |     else if (!ch && !scintilla_send_mouse(view, event, button, y, x, shift, ctrl, alt) &&
      |                      ^~~~~~~~~~~~~~~~~~~~
In file included from textadept.c:58:
scintilla/curses/ScintillaCurses.h:63:6: note: declared here
   63 | bool scintilla_send_mouse(void *sci, int event, unsigned int time, int button, int y, int x,
      |      ^~~~~~~~~~~~~~~~~~~~
textadept.c:2621:7: error: too few arguments to function 'scintilla_send_mouse'
 2621 |       scintilla_send_mouse(focused_view, event, button, y, x, shift, ctrl, alt);
      |       ^~~~~~~~~~~~~~~~~~~~
```

**Comment by orbitalquark** [comment]
Are you trying to build 11.4 itself, or the latest nightly?

If you're trying to build 11.4, checkout the 11.4 tag. The nightly builds use that problematic function call, but 11.4 does not. (https://github.com/orbitalquark/textadept/commit/3d1edd40f90ad2a41d099bd877be0faa2538b649)

If you're trying to build the latest nightly, make sure you run `make deps NIGHTLY=1` first to grab the latest Scinterm.

**Comment by paaguti** [comment]
Latest nightly…

Enviado desde mi iPhone

**Comment by orbitalquark** [comment]
I'm going to close this because the nightlies are building properly and I'm assuming you didn't run `make deps NIGHTLY=1` first. The nightly builds do this.
