### ISSUE TITLE
Improvements to the Ada lexer

### ISSUE THREAD

**Issue by jcprpr** [orbitalquark/textadept#268]
There are some simple changes that could be done to improve the Ada lexer:
1. Ada is not case sensitive.
2. Ada 2022 added the reserved word `parallel`. Additionally, apparently the reserved words `overriding` and `some` were missing. [Here](http://www.ada-auth.org/standards/22rm/html/RM-2-9.html) is a full list.

Also, you might want to fix privilages -> privileges on the textadept homepage.

**Comment by orbitalquark** [comment]
Thanks for the heads up, I will look into this when I have some time.

**Comment by orbitalquark** [comment]
Ada improvements were committed in Scintillua: https://github.com/orbitalquark/scintillua/commit/9fd3ed6d4f13458a11a8fc38dd6aa3ded72f3c48.
