### ISSUE TITLE
The `case` field in style definition yields an error since version 11.5 alpha

### ISSUE THREAD

**Issue by davidvontamar** [orbitalquark/textadept#274]
The `case` field in style definition doesn't work. However, the 11.5 alpha API [lists](https://orbitalquark.github.io/textadept/api.html#view.styles) `case` under `view.styles` with the possible values `u`, `l`, or the default `m`. The following code does not work and will yield an error.
```
styles.keyword = {
	case = "u"
}
```
The error:
```
/usr/local/share/textadept/core/init.lua:95: bad argument #3 to 'newindex' (number expected, got string)
```

**Comment by orbitalquark** [comment]
Thanks for the report. I need to change the documentation. The proper values are now `view.CASE_MIXED` (the default), `view.CASE_UPPER`, `view.CASE_LOWER`, and `view.CASE_CAMEL`.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/textadept/commit/52d83847b2254a512f6bfd1bec0d7eb6af36370c
