### ISSUE TITLE
auto_c_choose_single defaults to `true`

### ISSUE THREAD

**Issue by eric-hemasystems** [orbitalquark/textadept#275]
The documentation says this defaults to `false` but it seemed to be `true` on my machine and I am guessing [this init.lua](https://github.com/orbitalquark/textadept/blob/c78944f2e59ec9ccd69cc40d57de3ae0726f4078/init.lua#L229) is what is making that happen.

Would have submitted a PR to update the documentation but I wasn't sure what is the canonical source of the documentation:

* [option 1](https://github.com/orbitalquark/textadept/blob/c78944f2e59ec9ccd69cc40d57de3ae0726f4078/core/.buffer.luadoc#L47-L50)
* [option 2](https://github.com/orbitalquark/textadept/blob/1dbcff60ec070a1881090ce8669ff1214244188f/modules/lua/ta_api#L378)
* [option 3](https://github.com/orbitalquark/textadept/blob/1dbcff60ec070a1881090ce8669ff1214244188f/docs/api.md?plain=1#L926-L931)

I'm thinking option 1 and the other two are generated?

**Comment by orbitalquark** [comment]
Option 1 is the true source. 2 and 3 are generated from 1. The documented default values are based on Scintilla's defaults. This helps me figure out what to set in Textadept's *init.lua* without having to look it up. I prefer to keep it this way.

**Comment by eric-hemasystems** [comment]
Ah, ok. So the documentation is not the default of Textadept but the default of Scintilla. In that case will close.
