### ISSUE TITLE
EOL annotations ignore the `back` field in styles

### ISSUE THREAD

**Issue by davidvontamar** [orbitalquark/textadept#276]
I don't know why, but it seems that the `back` field is completely ignored by EOL annotations (I haven't tested it on the regular annotations, so they should be checked too). Here's a simple style that will reproduce this:
```
view.styles["error"] = {
	fore = 0XFFFFFF,
	back = 0X0000FF
}
```
The style is then applied via the `view.indic_style` table.

**Comment by orbitalquark** [comment]
Thanks for the report. I'll take a look into this when I have some time.

**Comment by orbitalquark** [comment]
This looks like a Scintilla issue when `view.annotation_visible` is `view.EOLANNOTATION_STANDARD` or `view.EOLANNOTATION_BOXED`. If you use any other style like `view.EOLANNOTATION_FLATS`, then it works. I'll report this upstream.

**Comment by orbitalquark** [comment]
This was fixed in Scintilla and should also be fixed in the next nightly build: https://github.com/orbitalquark/textadept/commit/8a933205607fe9eb2127193a76cc4bbcd2b44ffe. Sorry for the delay.
