### ISSUE TITLE
Textadept WIN build for portableapps.com

### ISSUE THREAD

**Issue by amay5267** [orbitalquark/textadept#278]
Hi @orbitalquark 
Since Textadept is written mainly in C, it should be easily portable and packaged for https://portableapps.com/
What do you think? Is anybody interested into it?

**Comment by rgieseke** [comment]
I built a wrapper 12 years ago: https://github.com/rgieseke/textadept-portable

Not sure if it would still work or if the portable app ecosystem has changed since then.

It should still be easy since the app is self-contained and one only needs to re-route the `.textadept` config.

**Comment by orbitalquark** [comment]
Yes, Textadept can be run as a portable application. The manual mentions this: https://orbitalquark.github.io/textadept/manual.html#running (search for "portable" and you'll see it in that section).

The zip download is already portable, just extract and go. You'd need the additional step(s) mentioned in the manual if you want to keep *~/.textadept* on your flash drive or whatnot.

I don't know what "packaging for portableapps" entails, but I probably wouldn't want to package specifically for it. If there's something I can do with the default zip to help, then please let me know and perhaps I can do something about it.

**Comment by amay5267** [comment]
Hi @rgieseke 
This is exactly what I was looking for.
Thanks for helping. 
A lot has changed since than.
NSIS is currently at 3.08
Textadept switched from Gtk2 to newer GTK…
Can you please update the scripts?

**Comment by amay5267** [comment]
Hi @orbitalquark 
Packaging for portableapps.com is exatly that scripts by @rgieseke.
When @rgieseke updates the scripts, can you test it with WINE ( winehg.org )?
When it works, you can provide TextadeptPortable.zip (your Win binary + launcher by @rgieseke .
