### ISSUE TITLE
OSX on nightly explodes when adding any argument

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#293]
```
~ ➤ /Applications/Textadept.app/Contents/MacOS/textadept_osx
~ ➤ /Applications/Textadept.app/Contents/MacOS/textadept_osx .textadept/init.lua

objc[19934]: autorelease pool page 0x7fee8918e000 corrupted
  magic     0x00000001 0x00000000 0x00000000 0x00000000
  should be 0xa1a1a1a1 0x4f545541 0x454c4552 0x21455341
  pthread   0x0
  should be 0x107714600

[1]    19934 abort      /Applications/Textadept.app/Contents/MacOS/textadept_osx .textadept/init.lua
```

Opens correctly if and only if I do not add the files I want to open.
```
~ ➤ uname -a
Darwin paag-MacBookAir 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

**Comment by orbitalquark** [comment]
Thanks for the report. Have you tried using the *ta* script distributed with the releases? That's the intended way to execute Textadept from the command line. Executing the binary directly can be dangerous as you're experiencing.

**Comment by paaguti** [comment]
The `ta` script or using directly `open -a TextAdept <file>` will open TextAdept on an empty buffer.

**Comment by orbitalquark** [comment]
I am not able to reproduce this issue on macOS. I used both `ta [path to file]` and `open -a Textadept.app [path to another file]` and in both cases Textadept opened the file in question. I also tried this while Textadept is running and everything worked as expected. I don't know what's going wrong :(

**Comment by paaguti** [comment]
Doesn’t happen with todays nightly w/ Qt. Didn’t have time to check again…Enviado desde mi iPhoneEl 29 dic 2022, a las 3:26, orbitalquark ***@***.***> escribió:﻿
I am not able to reproduce this issue on macOS. I used both `ta [path to file]` and `open -a Textadept.app [path to another file]` and in both cases Textadept opened the file in question. I also tried this while Textadept is running and everything worked as expected. I don't know what's going wrong :(
