### ISSUE TITLE
Fonts look very faint, low contrast and thin on win32 version

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept#295]
A picture is worth a thousands words:

![textadept](https://user-images.githubusercontent.com/117802029/202557556-1eac55b5-3c28-4184-bf5f-560e108455db.PNG)

![geany](https://user-images.githubusercontent.com/117802029/202557575-6f28734c-eedf-4106-a3c8-299e08491c35.PNG)

Both editors are GTK3 based and make use of FreeType. So why there is such a different?

**Comment by ghost** [comment]
Note: both editors are using font Consolas size 11, I set screen scaling to 125%. I'm on Windows 8.1 64 bit.

**Comment by ghost** [comment]
Because of the Windows scaling setting, the pictures are somehow zoomed. On my computer it's not look like that. But it's still good enough to tell what's going on.

**Comment by orbitalquark** [comment]
The latest alpha has a new, higher contrast theme that may help. It cannot be used with 11.4, but it'll give an idea of what you can do to improve 11.4's default theme.

Based on your screenshot, it looks like Geany uses bold font faces for keywords. Textadept does not use bold fonts at all in its default theme. Font thinness is probably caused by a difference in GTK runtime versions. I'm not sure what can be done about that.

**Comment by ghost** [comment]
> The latest alpha has a new, higher contrast theme that may help. It cannot be used with 11.4, but it'll give an idea of what you can do to improve 11.4's default theme. Based on your screenshot, it looks like Geany uses bold font faces for keywords. Textadept does not use bold fonts at all in its default theme. Font thinness is probably caused by a difference in **GTK runtime versions**. I'm not sure what can be done about that.

Or the way you configured FreeType. I just know you are about to drop BSD support. It's already evil enough to set Linux as a hard requirement to be able to build and only cross compile to other platforms like they are second class citizens. Now you are going to drop support for BSD. What about being a Linux only text editor? Why is there a Windows version? I will stick with Geany. Bye.
