### ISSUE TITLE
cilcking on error message of "go run/build" does not open the file

### ISSUE THREAD

**Issue by bokunodev** [orbitalquark/textadept#3]
go run/build errors are highlighted. but clicking on it doesn't open the file.
first I thought it was because the pattern didn't match the error message.
so I changed it to ``(.-):(%d+):(%d+):([^\n]+)``
and i got this error mesage
``lua: /usr/local/share/textadept/modules/textadept/run.lua:100: attempt to index a nil value (field 'filename')``

i made my own go extension to automatically format and import every i save the file.
i use the same pattern to match goimports errors and its works.

**Comment by orbitalquark** [comment]
What version of Go? What is the error message? (Feel free to replace your filename with something generic).

**Comment by bokunodev** [comment]
latest go 1.15.6
its just a normal systax error.

**main.go**
```go
package main

import "goserve/src/share/server"

func main()
	_ = server.New()
}
```
**error message**
```text
> cd /home/user/go/path/goserve/src
> go run /home/user/go/path/goserve/src/main.go
# command-line-arguments
./main.go:5:6: missing function body
./main.go:6:2: syntax error: non-declaration statement outside function body
> exit status: 512
```

**Comment by orbitalquark** [comment]
Try `textadept.run.error_patterns.go = {'^(.-):(%d+):(%d+): (.+)$'}`. It's possible the lack of a starting anchor in your pattern is to blame.

**Comment by bokunodev** [comment]
oh, thanks. it wokrs.

**Comment by orbitalquark** [comment]
I have updated the default Go error patterns: https://github.com/orbitalquark/textadept/commit/ba1f5b94a33e8c586593b62143f22f9e0c4b7bb5
