### ISSUE TITLE
CMAKE_INSTALL_PREFIX creates weird link when creating .deb package

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#303]
The link creating needs to be changed. The current source is
`${ta_data_dir}/textadept`
and that comes from
`set(ta_data_dir ${CMAKE_INSTALL_FULL_DATADIR}/textadept)`
which creates a weird link:

```
lrwxrwxrwx 1 root root    68 dic  6 16:12 /usr/bin/textadept -> /home/devel/textadept/debian/textadept/usr/share/textadept/textadept
```

**Comment by orbitalquark** [comment]
This is has been fixed via https://github.com/orbitalquark/textadept/commit/17f868dbe58fd75a630a01f19d697461c5f1a7e5 as noted in #304 .
