### ISSUE TITLE
Incorrect handling of an UTF-8 encoded file with embedded control codes.

### ISSUE THREAD

**Issue by Selorax** [orbitalquark/textadept#305]
I use freshly built Text Adept 11.4. Upon opening some files it determines the encoding incorrectly and Buffer -> Encoding -> UTF-8 does not fix it. An example of file attached. The file is a valid UTF-8 text with C0 control characters which are included in ASCII set so must be treated as UTF-8 text.
[enc_test.txt](https://github.com/orbitalquark/textadept/files/10200097/enc_test.txt)

**Comment by Selorax** [comment]
In fact there are several bugs in one:
a) The UTF-8 encoding was not detected automatically.
b) `Buffer -> Encoding -> UTF-8 Encoding` didn't work
c) When I tried to force UTF-8 by going `File -> Reload`, data after NULL character was lost

**Comment by orbitalquark** [comment]
Textadept has an assumption that UTF-8 text does not include any NUL bytes. If you remove the NUL byte from your test file, Textadept correctly identifies it as UTF-8. If the file contains NUL bytes, then Textadept tries UTF-16 (or 32 if you have it configured).

I admit I am not well versed at all in file encodings, so I don't really know the best way to handle this.

**Comment by Selorax** [comment]
Well, for UTF-8 I can recommend trying to decode the file as UTF-8, and if the file can be decoded, assume it's UTF-8. Null bytes are valid there. Then, if there are invalid UTF-8, and lots of null bytes, you can try UTF-16 or UTF-32, if there are little or no null bytes, then `latin1` / `cp1252` makes sense and so on.  Valid UTF-8 is defined as sequences of bytes having bit representations of either `0.......` (that's ASCII, including `^@` / `NUL` character among other things), or `110..... 10......` or `1110.... 10...... 10......` or `11110... 10...... 10...... 10......` and so on, where number of 1s before first 0 equals to number of bytes in the sequence, though sequences longer than four bytes are currently and in foreseeable future are going to be unassigned.

Either way, please try to make sure the editor is binary safe, as in editing a binary file and saving it doesn't break it, if you preserve length and disable auto-formatting features.

Anyway, the more severe problem here is I cannot set the encoding correctly. So maybe you can add an encoding selector in file picker for ^O and maybe ^S? Both could be "Auto" by default.

Or just assume UTF-8 and let the user select something else if the encoding is different. For example I have some files in cp866 and TextAdept can't recognize them at all.

@orbitalquark, can you suggest how to disable encoding auto-detection and always assume UTF-8 for a temporary fix, until you make a new release with this problem fixed, please?

**Comment by orbitalquark** [comment]
The easiest solution was to allow UTF-8 to be attempted in detection of files with NUL bytes: https://github.com/orbitalquark/textadept/commit/43a186069317c11369e7087d5e1b77ae6c859667. If a file containing NUL bytes is not valid UTF-8, then UTF-16/32 is tried. Otherwise detection proceeds as normal, falling back on a binary file. The original goal was to not allow binary files (which often have NUL bytes) to be detected as UTF-8. The unit tests with this change are passing, and opening some random binary files on my Linux box appear to be opened as binary files.

Thanks for your input.

**Comment by Selorax** [comment]
@orbitalquark 

Thanks, the test file opens alright now, however `File -> Reload` menu command still loses part of file after first NUL byte. 
I still have 11.4, but I have applied your fix to my installation.

**Comment by orbitalquark** [comment]
Oops, sorry about that. This should be fixed via https://github.com/orbitalquark/textadept/commit/75a53f025a322464bb56faaf970fa36adc0f0aba.
