### ISSUE TITLE
Feature request: include standard definition for INDIC_WARN and INDIC_ERROR in modules/textadept.lua

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#315]
It would be useful both for module and for theme writers to have these two defined and accessible. 
They are used in LSP and may be  used in other modules and it would be great to have them uniformly defined in your theme.

**Comment by orbitalquark** [comment]
Thanks for letting me know. I will look into this.

**Comment by orbitalquark** [comment]
Added via https://github.com/orbitalquark/textadept/commit/7d34480b923d7c362e7694f73739f5b336371ca0
