### ISSUE TITLE
Disabling vertical scroll bar also disables mouse wheel scrolling

### ISSUE THREAD

**Issue by snoopy** [orbitalquark/textadept#317]
Disabling the vertical scroll bar via `view.v_scroll_bar = false` also disables mouse wheel scrolling for me.
Tested with Textadept nightly (27 Dec 2022).

**Comment by orbitalquark** [comment]
Yes, I noticed that too. The Scintilla Qt component does this intentionally. I haven't yet asked on the Scintilla mailing list if this is still desired behavior.

**Comment by orbitalquark** [comment]
I've patched Scintilla to enable wheel scrolling even if scrollbars are disabled: https://github.com/orbitalquark/textadept/commit/e7f8a485de68baad44f703a4a1e3fda941d0a630

I've also inquired on the Scintilla mailing list if this default behavior can be changed.
