### ISSUE TITLE
elastic tabstops are not working

### ISSUE THREAD

**Issue by dicktyr** [orbitalquark/textadept#32]
elastic_tabstops/init.lua:307: attempt to perform arithmetic on a string value (local 'length')
elastic_tabstops/init.lua:307: attempt to perform arithmetic on a nil value (local 'length')

**Comment by orbitalquark** [comment]
Unfortunately, that third-party module is marked on the wiki as only working for 10.x[1]. It will have to be updated by some knowledgable user for 11.0.

[1]: https://github.com/orbitalquark/textadept/wiki#stuff-only-working-for-10x

**Comment by dicktyr** [comment]
thanks
I put a notice about that on the [wiki page](https://github.com/orbitalquark/textadept/wiki/elastic-tabstops)

I'm surprised that elastic tabstops are not more widely appreciated

they're certainly an unconditional requirement for me
when viewing/editing tabular data

**Comment by joshuakraemer** [comment]
A new and improved Elastic Tabstops module is now available here: https://github.com/joshuakraemer/textadept-elastic-tabstops
I have changed the wiki accordingly.

**Comment by dicktyr** [comment]
@joshuakraemer thank you kindly
