### ISSUE TITLE
Erratic scrolling after centering view

### ISSUE THREAD

**Issue by snoopy** [orbitalquark/textadept#330]
When centering the current line via `view:vertical_center_caret()` and scrolling with the mouse afterwards the scrolling jumps unpredictably. Seems like scrolling is not done from the current line but some other position.

**Comment by orbitalquark** [comment]
This should be fixed via 
https://github.com/orbitalquark/textadept/commit/ee119292a1ceb301d098dfbfa612910a91584fe6. 
I've submitted an upstream patch to Scintilla for this issue.
