### ISSUE TITLE
Problem with bash parser

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#334]
I fear that the `bash` parser chokes at escaped quotes:

![image](https://user-images.githubusercontent.com/3320432/211753182-f1e61124-0e4f-4a56-8d67-d8b47a51b95b.png)

This is on Textadept nightly with Qt.

**Comment by orbitalquark** [comment]
Thanks for the report. This should be fixed in Scintillua: 
https://github.com/orbitalquark/scintillua/commit/b6f6c040fa914d45c2d55f099cee985253d13cdc. 
It will show up in the next nightly build.
