### ISSUE TITLE
org directive isn't highlighted in 'asm' lexer

### ISSUE THREAD

**Issue by Selorax** [orbitalquark/textadept#335]
'org' is the directive of the assembly language to tell the assembler that next code will be loaded at a specific address in memory.

**Comment by Selorax** [comment]
Also, a question, is it possible to highlight assembly labels and constants defined with EQU in the current file?

Though that would make lexer dynamic in a sense, as in, what it highlights depends on the content of opened file. You might also want to add definitions from include files, but that's going to be another level.

However it would let the user easily spot mistypes such as
```
print_string EQU 0F809h
exit EQU 0F800h
org 100h
	jmp satrt:
hello_world_string:
	db "Hello, world!", 10, 0
start:
	mov a, hello_wrld_string
	call priint_string
	call exit
```

**Comment by orbitalquark** [comment]
I think it can be done, but I'm not sure how accurate or performant it 
would be.

**Comment by orbitalquark** [comment]
'org' was added in Scintillua: https://github.com/orbitalquark/scintillua/commit/09a1804862300103034d43c2a723cc5b0cbec521. It will be in the next nightly build.

Reference: https://www.nasm.us/doc/nasmdoc8.html#section-8.1.1
