### ISSUE TITLE
10.5 alpha_2 scrolling issue

### ISSUE THREAD

**Issue by audiofool** [orbitalquark/textadept#337]
1. Open a file
2. scroll down say 100 lines
3. Open 2 new tabs, can be untitled or actual files 
4. Click on 1st tab opened to change focus and then close the tab
5. Click on originally opened file -> it has now scrolled by itself to the top of the file??

**Comment by orbitalquark** [comment]
Thanks for the report. I'll look into this when I have some time.

**Comment by orbitalquark** [comment]
This should be fixed via 
https://github.com/orbitalquark/textadept/commit/ceb95b122461d139f49f8502ac6647743815a697 
and will be in the next nightly build.
