### ISSUE TITLE
[Freebsd 13.1] ctrl+f box does not accept input.

### ISSUE THREAD

**Issue by Nomarian** [orbitalquark/textadept#346]
### VERSION
11.4

### OS
FreeBSD 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

### ERROR MESSAGE
None

### WARNING MESSAGE
None

### UI
gtk3,gtk2

There's not much to go on and there's no error/warning message, While the textbox does not accept input, It does exit with ESC

Additional notes:

Textbox can be highlighted and copy/pasted inside. the buttons work. all the other textboxes work as well. even the command entry box.

**Comment by orbitalquark** [comment]
Sorry to hear :( I don't have a BSD machine to test on, so there's 
nothing I can do here.

**Comment by orbitalquark** [comment]
Closing, as BSD has not been supported for some time. Sorry :( If it ever does work again, there's always the Qt version that may not have this issue.
