### ISSUE TITLE
Add Objeck lexer

### ISSUE THREAD

**Issue by 1997tn** [orbitalquark/textadept#347]
This is the Objeck language: https://github.com/objeck/objeck-lang

There are syntax highlighting rules available for several editors but unfortunately none for TextAdept yet.

https://github.com/objeck/objeck-lang/tree/master/docs/syntax

**Comment by ghost** [comment]
Draft: https://github.com/iqskpduswupkcjqg/textadept-objeck-lexer/blob/main/objeck.lua
