### ISSUE TITLE
[request] Is it possible to create lexer for _hyperscript?

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept#357]
### Discussed in https://github.com/orbitalquark/textadept/discussions/352

<div type='discussions-op-text'>

<sup>Originally posted by **iqskpduswupkcjqg** February  4, 2023</sup>
https://hyperscript.org/docs/

https://github.com/gnat/hyperscript-sublime/

https://github.com/dz4k/vscode-hyperscript</div>

I'm unable to do it myself. Please make a lexer for _hyperscript when you have time. Thank you.

**Comment by orbitalquark** [comment]
I have added this to the Scintillua issue tracker: 
https://github.com/orbitalquark/scintillua/issues/89, as that's where it 
will ultimately go.
