### ISSUE TITLE
Wrong release date in latest changelog entry

### ISSUE THREAD

**Issue by richbowen** [orbitalquark/textadept#364]
![orbitalquark github io_textadept_changelog html](https://user-images.githubusercontent.com/5672238/220476514-d82f1ee2-6980-48e7-9945-fec01397b4c9.png)

**Comment by orbitalquark** [comment]
The upcoming 12.0 alpha 2 is slated for release on 1 March 2023. This is 
a running list of changes since the first alpha's release, primarily for 
those following the progress of the nightly builds.

Sorry for the confusion :(
