### ISSUE TITLE
Make the TextAdept app themeable

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept#375]
> Btw, you always said you can't implement theming for TextAdept (I mean the TextAdept app, not the editor color scheme you called theme). You always said it's because the limitations of GTK and Qt so you can't do anything with it. The fact is, there is no such limitations. Both GTK and Qt support style sheets:
> 
> https://docs.gtk.org/gtk3/css-overview.html
> 
> https://doc.qt.io/qt-5/stylesheet-customizing.html
> 
> An example of a Qt app with out of the box dark theme: https://github.com/royqh1979/RedPanda-CPP

https://github.com/orbitalquark/textadept/discussions/368#discussioncomment-5286685

**Comment by orbitalquark** [comment]
The manual mentions using CSS stylesheets for theming Textadept's GUI: https://orbitalquark.github.io/textadept/manual.html#themes. If Qt has an equivalent, then that's on the user to change. I have no intention of allowing GUI theming from Textadept, as it should respect OS defaults to blend in like a good citizen.

There is an open ticket for supporting dark mode: #336.
