### ISSUE TITLE
Dark mode for the application

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept#387]
Please care a bit more for people using legacy versions of Windows. On Windows 10+ they have built-in support for Dark Mode. On Windows 7 and 8.1, the most close we have is High Contrast theme. Dark mode should be implemented by the application. Windows' Dark Mode feature is not always available.

**Comment by orbitalquark** [comment]
Both Windows 7 and Windows 8 are EOL, so I have no desire to add functionality specific to them. You can try using GTK themes or Qt stylesheets to mimic dark mode, depending on which version of Textadept you are running. However, I do not know how to use either, so you will have to figure that out on your own.

#336
