### ISSUE TITLE
Update Nim lexer to support multi-line comments

### ISSUE THREAD

**Issue by sigzero** [orbitalquark/textadept#39]
A multi-line comment in Nim is the following format:

#[
This is multi-line comment syntax.
]#

This can be supported in the nim lexer by changing the comment section to:

    -- Comments.
    local line_comment = lexer.to_eol('#', true)
    local block_comment = lexer.range('#[', ']#')
    lex:add_rule('comment', token(lexer.COMMENT, block_comment + line_comment))

**Comment by orbitalquark** [comment]
Thanks! Fixed via https://github.com/orbitalquark/scintillua/commit/abac71e0b9f025b89176c0363117b755f2de0038

This should show up in the next nightly build.
