### ISSUE TITLE
.gitignore file

### ISSUE THREAD

**Issue by rgieseke** [orbitalquark/textadept#40]
To keep a cleaner state when building Textadept locally it would be nice if Textadept would ship with a `.gitignore` file:

I think the following content should keep a clean state:

```
textadept*
lexers/
src/cdk/
src/gtdialog/
src/LexLPeg.*
src/lua/
src/scintilla/
src/termkey/
src/*.o
src/*.tar.gz
src/*.tgz
src/*.zip
```

**Comment by orbitalquark** [comment]
Thanks for the suggestion. Fixed via https://github.com/orbitalquark/textadept/commit/7e85ba716ddd9718e94642422c98533449f44e9e.

Note that I use Mercurial behind the scenes, so I cannot test this. I'll take your word for it that it works.

**Comment by rgieseke** [comment]
Thanks for the quick fix!
Looks good, affter `make textadept`
```
On branch default
Your branch is up to date with 'origin/default'.

nothing to commit, working tree clean
```

**Comment by orbitalquark** [comment]
Looks like this change broke the nightly build:

    [snip]
    mkdir -p Textadept.app/Contents/MacOS Textadept.app/Contents/Resources
    cp Info.plist Textadept.app/Contents/MacOS/../
    cp ../textadept ../textadept-curses ../scripts/osx/textadept_osx Textadept.app/Contents/MacOS/
    cd ../ && git archive HEAD --prefix src/Textadept.app/Contents/Resources/ | tar -xf -
    cp -rL ../docs ../lexers Textadept.app/Contents/Resources
    mv Textadept.app/Contents/Resources/core/images/textadept.icns Textadept.app/Contents/Resources/
    mv: cannot stat 'Textadept.app/Contents/Resources/core/images/textadept.icns': No such file or directory

I think `git archive` takes *.gitignore* into account and ignores *textadept.icns*. I've removed `textadept*` from *.gitignore* for now via https://github.com/orbitalquark/textadept/commit/fc0687d77aa00051cf2606b74c886f3141736ad7

**Comment by rgieseke** [comment]
Sorry for the trouble!
Having the two binaries in `git status` outbput isn't a big deal ...
One could probably list them explicitly
```
# Binaries.
src/*.o
src/*.tar.gz
src/*.tgz
src/*.zip
textadept
textadept-curses
```

I've tested `git archive HEAD --prefix src/Textadept.app/Contents/Resources/ | tar -xf -`
And this includes `textadept.icns`.

**Comment by orbitalquark** [comment]
Okay, committed via https://github.com/orbitalquark/textadept/commit/c66ed5b1074e1b5839a2c63156ba3d60f39faf9e and I just ran a successful nightly build. Thanks.
