### ISSUE TITLE
Enhancement suggestion: Change default keyboard shortcut for Upper Case Selection

### ISSUE THREAD

**Issue by chrisgeli** [orbitalquark/textadept#403]
This shortcut is (in the 12.0 alpha 3) `ctrl+U` which clashes with the default shortcut for [Linux Unicode input](https://en.wikipedia.org/wiki/Unicode_input#In_X11_(Linux_and_other_Unix_variants_including_ChromeOS)), which makes the shortcut impossible to use in Textadept (the Unicode input takes precedence), at least on my Debian 12 system running XFCE.

Additional info:
```
$ find /opt/textadept/ -name '*.lua' -exec grep -Hi 'ctrl+U' {} \;
/opt/textadept/modules/textadept/keys.lua:-- Ctrl+U | ⌘U | ^U | Lower case selection
/opt/textadept/modules/textadept/keys.lua:-- Ctrl+Up | ⌥⇡ | ^Up | Paragraph up
/opt/textadept/modules/textadept/keys.lua:  [m('Edit/Selection/Upper Case Selection')] = {'ctrl+U', 'cmd+U', 'ctrl+meta+u'},
/opt/textadept/modules/textadept/keys.lua:  [m('Edit/Selection/Lower Case Selection')] = {'ctrl+u', 'cmd+u', 'ctrl+u'},
/opt/textadept/modules/textadept/keys.lua:  [buffer.para_up] = {'ctrl+up', 'alt+up', 'ctrl+up'},
/opt/textadept/core/keys.lua:--     keys['ctrl+u'] = function() io.quick_open(_USERHOME) end
```
Minor aside: The comment in *core/keys.lua* seems to be outdated.

For now, I mapped it as follows in my *~/.textadept/init.lua*:
```
keys['ctrl+alt+u'] = textadept.menu.menubar[_L.Edit][_L.Selection][_L['Upper Case Selection']][2]
```
Thanks for your time!

**Comment by orbitalquark** [comment]
Thanks for the report. I will add an alias, likely either "Ctrl+Alt+U" or "Ctrl+Alt+Shift+U". My Kubuntu 22.04 does not hijack "Ctrl+Shift+U", so I didn't experience the clash.

**Comment by orbitalquark** [comment]
I've addressed this in https://github.com/orbitalquark/textadept/commit/3111f9ec4f9f8ca8d0f4cbe7f023ab564880f335
