### ISSUE TITLE
Can't compile if folder name (in the path) has parentheses

### ISSUE THREAD

**Issue by AmbitiousAlan** [orbitalquark/textadept#404]
Steps to reproduce:
-Download zip file of the code on github
-Download zip file of the code on github
-Now you have textadept-default(1).zip
-Follow steps to compile 
-Doesn't compile

Granted. Once you understand it breaks because of parentheses, you can just rename the folder and all works. But this issue is here so at least if someone else encounters the same problem, they might find this issue and figure it out.

Otherwise, a temporary fix would just be putting an assert statement somewhere in the cmake or code to throw an error if your path has parentheses or something (and tell the user to rename the folder in the path).

**Comment by paaguti** [comment]
That's a browser problem. I use git to get a clean and consistent copy from github

Enviado desde mi iPad

**Comment by AmbitiousAlan** [comment]
This has nothing to do with the browser. I have not tested it, but I suspect that parentheses anywhere in the path breaks compilation. While I had parentheses because I downloaded it twice, someone could just decide to use parentheses in the name of their workfolder and that would also break compilation.
As implied in the original issue, this is very minor. I can't imagine many people using parentheses in the name of a folder and most people, like you paaguti, uses git.

Regardless, adding a warning or an assert somewhere that checks for parentheses in the path might just save time for a user somewhere.

**Comment by orbitalquark** [comment]
What OS are you on? I was unable to reproduce the issue on Linux. Parentheses in the directory name did not cause any issues.

Also, what was the error?

**Comment by AmbitiousAlan** [comment]
I use ubuntu desktop 22.04. I will provide the error message I got once I get home.

**Comment by AmbitiousAlan** [comment]
```
-- Install configuration: "RelWithDebInfo"
-- Installing: /mnt/sdb1/textadept-default(1)/textadept-default/build_dir/install/share/textadept/textadept-gtk
CMake Error at build_dir/cmake_install.cmake:78 (file):
  file unknown argument: "("
```

This was the error.

Also:

```
alan@alan:/mnt/sdb1/textadept-default(1)/textadept-default$ ls
'('   build_dir        docs       modules     src
')'   CMakeLists.txt   init.lua   README.md   test
 1    core             LICENSE    scripts     themes
```
It creates three folders named '(', '1', ')'.

**Comment by AmbitiousAlan** [comment]
I am not sure it is worth the effort to troubleshoot this. It's not causing me any issues.

**Comment by orbitalquark** [comment]
This seems like a CMake issue. I don't understand why it's creating '(', 
'1', and ')' files.
