### ISSUE TITLE
Version 12 doesn't show unsaved buffers when entering * in Switch to Buffer dialog

### ISSUE THREAD

**Issue by chrisgeli** [orbitalquark/textadept#409]
In version 11, I used to find unsaved buffers easily by hitting `ctrl+b` and `*` which is the prefix of the Name column entries that have unsaved changes. That is not the case in version 12, which doesn't seem to filter anything when I enter asterisks.

Unless there is a good reason for this change, I would like to kindly request the old behaviour back.

Thanks for your continued improvements to Textadept!

**Comment by orbitalquark** [comment]
Thanks for the report. It was not intentional. It works in the Gtk version, but not Qt. Should be fixed in the next nightly build via https://github.com/orbitalquark/textadept/commit/e19178159380ae8fcbbdcd54faca34e63e8ebfd0
