### ISSUE TITLE
[nightly] "Insert Snippet..." fails with error if no snippets are defined

### ISSUE THREAD

**Issue by shadowbanned-by-gh** [orbitalquark/textadept#414]
```
/usr/share/textadept/modules/textadept/snippets.lua:775: bad argument #1 to 'list' (non-empty 'items' table expected)
```
In 11.4 the Insert Snippet dialog does show up (with empty list).

**Comment by orbitalquark** [comment]
Thanks for the report! Fixed via https://github.com/orbitalquark/textadept/commit/934ece9d5b0011bac8149b39b2145ca76a0934cd
