### ISSUE TITLE
12.0 beta still does not highlight python-3.10 syntax

### ISSUE THREAD

**Issue by grozin** [orbitalquark/textadept#425]
match and case are not highlighted

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/58fc3a9588051c556903afa99c449a96a7396ac6 and should be in the next nightly build.

You can disable soft keyword highlighting by putting `styles.keyword_soft = {}` in your theme file.

**Comment by orbitalquark** [comment]
Actually, the default should be to not highlight soft keywords. It should be opt-in.

Therefore with https://github.com/orbitalquark/textadept/commit/e5741bf91fd88c71dd94470d28b77b45f66af224 you'll need to explicitly enable soft keyword highlighting in your theme by putting `styles.keyword_soft = styles.keyword` in your theme.
