### ISSUE TITLE
Donation link / button broken

### ISSUE THREAD

**Issue by jxzwp** [orbitalquark/textadept#429]
When you click on the Donate button at the top right of https://orbitalquark.github.io/textadept/index.html or the Donate link at the top of https://orbitalquark.github.io/textadept/changelog.html

It loads a paypal webpage that says "This organisation's page is broken."

I tried this in different browsers with all ad blocking disabled.

**Comment by orbitalquark** [comment]
I have removed the broken links. If you or anyone else wishes to make a donation, please contact me by e-mail, which is at the bottom of the README.
