### ISSUE TITLE
Bug: subscript character error

### ISSUE THREAD

**Issue by humphreylee** [orbitalquark/textadept#431]
Encountered issue to load subscript character in the latest/nightly version. See screenshot below. On the left windows is textadept, while on the right is another editor. Appreciate your assistance. Thanks.

![textadept_subscript](https://github.com/orbitalquark/textadept/assets/66808535/e0352d44-8ac1-422b-8072-b1f6e2467969)

**Comment by orbitalquark** [comment]
To the right of the statusbar is the current buffer encoding. Is it UTF-8?

**Comment by humphreylee** [comment]
Yes, it is.  Below are snippet of my codes and screenshot with bottom statusbar. The same symbol in comment is displayed properly.
[sample julia file](https://github.com/orbitalquark/textadept/files/12188743/julia.txt)

![textadept2](https://github.com/orbitalquark/textadept/assets/66808535/b02abbf6-5fb0-429b-bd69-83d89567ef1d)

FYI, I use `Fira Code` font.
```
view:set_theme('dark', {font = 'Fira Code', size = 11})
```

**Comment by orbitalquark** [comment]
Ah, I see. The Julia lexer is to blame here. If you change the lexer to plain text or another lexer, the subscripts show up just fine. Thanks for the report. I'll look into this when I have time.

**Comment by humphreylee** [comment]
Thanks. I will leave this bug report open until the issue is fixed - OK?

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/304cff3ff3536b0ba757969a3e06a1072cc6a913 and should be in the next nightly build.
