### ISSUE TITLE
Query/ Feature Request: Print or Export to PDF

### ISSUE THREAD

**Issue by humphreylee** [orbitalquark/textadept#434]
Just wondering if there is such feature but hidden somehow? Thanks.

**Comment by orbitalquark** [comment]
Check out https://github.com/orbitalquark/textadept-export. It adds a "File > Export > Export to HTML..." menu option that exports to HTML and opens it in a browser. You can use your browser to print or convert to PDF.

**Comment by humphreylee** [comment]
Thanks for your prompt response. This helps.
