### ISSUE TITLE
Snippets don't work/cannot open dialog box.

### ISSUE THREAD

**Issue by aenlemmea** [orbitalquark/textadept#437]
Updated to 12.0 to find that snippets aren't working. Clicking on Tools>Snippets>Insert Snipet... should open the dialog box, but it doesn't. (As per the 12.0 Manual, it should I am assuming)

**Comment by orbitalquark** [comment]
You probably don't have any snippets defined. If you open the command entry (Tools > Command Entry), enter "snippets.foo='bar'", press Enter, then try Tools > Snippets > Insert Snippet..., it should work.

**Comment by aenlemmea** [comment]
I see. Figured it out. Thank you! Works as expected.
