### ISSUE TITLE
As you type auto indent

### ISSUE THREAD

**Issue by techntools** [orbitalquark/textadept#441]
How to get auto indent automatically ? I know there are settings about indent but I still am unable to find conf/script to perform indentation available in Vim/Neovim or Atom.

**Comment by orbitalquark** [comment]
Textadept does not have a feature to increase/decrease indent on syntax tokens like '{' for C-like languages, or control structure keywords like 'end' in Ruby. It only matches indentation on previous lines.

I had a feature in my *~/.textadept/init.lua* that auto-indented between auto-paired '{}' on 'Enter' that may be of help: https://github.com/orbitalquark/.textadept/blob/7294b433375f0e07ee2ba871087addf21129899b/init.lua#L195-L205

**Comment by techntools** [comment]
Ok. So, I need to write scripts/module.

Are there any existing ones ?

**Comment by orbitalquark** [comment]
I am not aware of any.
