### ISSUE TITLE
https://invisible-mirror.net unreachable

### ISSUE THREAD

**Issue by baraclese** [orbitalquark/textadept#442]
cdk is reachable for me at https://invisible-island.net/archives/cdk/cdk-5.0-20200923.tgz  - however I suggest to use the author's github repo at https://github.com/ThomasDickey/cdk-snapshots/archive/refs/tags/t20200923.tar.gz

**Comment by orbitalquark** [comment]
Thanks for the tip! Committed via https://github.com/orbitalquark/textadept/commit/d719064483cd0f8fb4ebce32dc937c0a18e418ad
