### ISSUE TITLE
--session parameter ignored

### ISSUE THREAD

**Issue by merlindiavova** [orbitalquark/textadept#449]
Hi

Running
```sh
$ textadept --session /path/to/session/file
```
does not loading the given session file, however
```sh
$ textadept -s /path/to/session/file
```
does load the session file?

Any ideas why this is?

Thanks

**Comment by orbitalquark** [comment]
Thanks for the report. Upon initial investigation, it looks like Qt 
gobbles up that argument. The GTK version allows Textadept to process 
it. I will have to look into this further.

**Comment by orbitalquark** [comment]
I've documented this unfortunate behavior in https://github.com/orbitalquark/textadept/commit/6ca8a41a6f01c17e14af3749b7156c81cff02f9d. I cannot figure out how to tell Qt to knock it off :(
