### ISSUE TITLE
Nightly build missing textadept module

### ISSUE THREAD

**Issue by brynne8** [orbitalquark/textadept#45]
(no description)

**Comment by rgieseke** [comment]
My bad, i guess ... 

https://github.com/orbitalquark/textadept/discussions/40

[Edit: fixed issue number)

**Comment by rgieseke** [comment]
The correct way seems to be to `.gitignore` with a leading slash

```
# Binaries.
src/*.o
src/*.tar.gz
src/*.tgz
src/*.zip
/textadept
/textadept-curses
```

>The slash / is used as the directory separator. Separators may occur at the beginning, middle or end of the .gitignore search pattern.
>
>If there is a separator at the beginning or middle (or both) of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. Otherwise the pattern may also match at any level below the .gitignore level.

http://git-scm.com/docs/gitignore

I've tested the above with a modification in `modules/textadept/snippets.lua`
The latter is shown as modified, the binaries in the project root are ignored.

**Comment by orbitalquark** [comment]
Third time's a charm: https://github.com/orbitalquark/textadept/commit/8908625df80ac87c9d3db79d2f5f657fc75875fa
