### ISSUE TITLE
Bottom slider/bar even on empty file (Linux)

### ISSUE THREAD

**Issue by jozsefk9** [orbitalquark/textadept#450]
Anyone knows why do I get a bottom slider/bar even on empty files?
![textadept-slider-1](https://github.com/orbitalquark/textadept/assets/1645288/6f2752ae-8ae5-49d1-9668-83dc3b4d4021)
![textadept-slider-2](https://github.com/orbitalquark/textadept/assets/1645288/c156b0f5-54b6-4c15-bc1d-302a250ff466)

**Comment by rgieseke** [comment]
I'm not sure what the reason is for the scrollbar appearing, but if you enable wrapping in your `init.lua` it should disappear

```lua
buffer.wrap_mode = buffer.WRAP_WORD
```

**Comment by jozsefk9** [comment]
> I'm not sure what the reason is for the scrollbar appearing, but if you enable wrapping in your `init.lua` it should disappear
> 
> ```lua
> buffer.wrap_mode = buffer.WRAP_WORD
> ```

Thank you. That worked!
