### ISSUE TITLE
Windows/VS2022/GTK3 build?

### ISSUE THREAD

**Issue by g40** [orbitalquark/textadept#454]
Hello. Interesting work. Thank you.

If I run the CMake GUI I can see no option to create a GTK build. Have I missed something?

FWIW [gvsbuild](https://github.com/wingtk/gvsbuild) makes it possible to get VS2022 to build all of the GTK3 suite. 

Best wishes.

**Comment by orbitalquark** [comment]
Unfortunately, GTK is not supported in Windows. It was in the past via cross-compilation from Linux, but since the switch to CMake, only Qt is supported on non-Linux platforms. If you wanted to invest the time, you could probably make it work. I don't know how though.

**Comment by g40** [comment]
Understood - thanks for the confirmation. I will take a look. Absolutely no promises but would you be amenable to a PR for this?

**Comment by orbitalquark** [comment]
I could be. It depends how much maintenance and support it would require (testing, packaging, etc.)

**Comment by orbitalquark** [comment]
I'm going to close this since due to inactivity.
