### ISSUE TITLE
Each consecutive invocation from the CLI spawns a new process

### ISSUE THREAD

**Issue by georgeraraujo** [orbitalquark/textadept#464]
Hi,

I just downloaded the 09/25 nightly (4a871b2) for Windows.

I deleted `%USERPROFILE%\.textadept` to start from scratch, and opened 5 files from the CLI:

```
textadept.exe 1st.txt
textadept.exe 2nd.txt
textadept.exe 3rd.txt
textadept.exe 4th.txt
textadept.exe 5th.txt
```

Each consecutive invocation from the CLI spawned a new process (five in total):

![image](https://github.com/orbitalquark/textadept/assets/4930759/f6a09722-4b5a-4bb1-8774-60f5eadda111)

As per the [nightly Manual](https://orbitalquark.github.io/textadept/manual.html#getting-started "nightly Manual"),

> The GUI version of Textadept is a single-instance application. **This means that after you start Textadept, any time you invoke it again (e.g. opening a file from a file browser or command line), the action happens in the original instance.**

Then I click "File", "Close All", and "File", "Quit", and still have 4 running processes:

![image](https://github.com/orbitalquark/textadept/assets/4930759/4c64ab39-0403-4d66-8a57-294707a9f21e)

I suppose that could be an issue.

**Comment by orbitalquark** [comment]
Thanks for the report! This should be fixed via https://github.com/orbitalquark/textadept/commit/bca2495acc6c9f495ee3d6963caa88da050a1452 and will be in the next nightly.
