### ISSUE TITLE
`view.element_color[view.ELEMENT_CARET]` and `ui.find.entry_font` in `~/.textadept/init.lua` have no effect

### ISSUE THREAD

**Issue by georgeraraujo** [orbitalquark/textadept#465]
Hi,

I just downloaded the 09/26 nightly (bca2495) for Windows (thanks for fixing #464!).

I deleted `%USERPROFILE%\.textadept` to start from scratch, clicked "Edit", "Preferences", and input the following code:

```lua
view:set_theme( 'light', { font = 'JetBrains Mono NL', size = 11 } )

ui.find.entry_font = 'Segoe UI 10'

view.caret_width = 2
view.element_color[view.ELEMENT_CARET] = 0x000099  -- red

view.edge_mode   = view.EDGE_LINE
view.edge_column = 80
```

Then I clicked "Tools", "Command Entry", and ran `reset()`. `view.element_color[view.ELEMENT_CARET]` and `ui.find.entry_font` didn't have any effect - the font in the "Find" and "Replace" entries remained the same as the one I set for the theme, and the caret remained black:

![image](https://github.com/orbitalquark/textadept/assets/4930759/77b0e7fa-d73c-40e9-a548-e0b41ce79b75)

Also, is there a way to display the number of buffers in the title bar?

Thanks for any attention.

**Comment by orbitalquark** [comment]
Those particular settings belong in a theme file (https://orbitalquark.github.io/textadept/manual.html#themes). Despite you setting them in your *~/.textadept/init.lua*, they are actually overwritten when the theme is applied. If you create and set your own theme, you should see what you expect.

As for displaying the number of buffers in the title bar, you can add to your *~/.textadept/init.lua*

https://github.com/orbitalquark/textadept/blob/3d868ac3f8d6c49bdf1941018bec1d988a30737e/core/ui.lua#L185-L191

and

https://github.com/orbitalquark/textadept/blob/3d868ac3f8d6c49bdf1941018bec1d988a30737e/core/ui.lua#L269-L274

Add a `%d` placeholder in the string on line 271 and a `#_BUFFERS` argument in the correct place. Your code will overwrite Textadept's setting of the title bar.

**Comment by georgeraraujo** [comment]
Thanks!
