### ISSUE TITLE
Editor View shows extraneous vertical lines next to a number of character boundaries at 150% scaling

### ISSUE THREAD

**Issue by georgeraraujo** [orbitalquark/textadept#466]
Hi,

I just downloaded the 09/27 nightly (3d868ac) for Windows. When I run it on a 1920x1080 laptop screen at 150% scaling, the Editor View shows extraneous vertical lines next to a number of character boundaries.

With 150% scaling it looks like this:

![image](https://github.com/orbitalquark/textadept/assets/4930759/3172ab43-9cce-449c-afca-d2b859fe6244)

With 100% scaling it looks right (this is on an RDP session):

![image](https://github.com/orbitalquark/textadept/assets/4930759/7e437ef3-51cd-4a95-8c53-2e31b5aef817)

**Comment by orbitalquark** [comment]
I'm pretty sure this is an issue with Scintilla (Textadept's editing component), so there's nothing I can do here :( You could try reporting it to the Scintilla mailing list (https://groups.google.com/g/scintilla-interest) or issue tracker (https://sourceforge.net/p/scintilla/bugs/). On Windows, Textadept is using the Qt platform for Scintilla.

**Comment by georgeraraujo** [comment]
I understand. Thanks!

**Comment by georgeraraujo** [comment]
The issue in Textadept could have to do with Qt, which SciTE (["a SCIntilla based Text Editor"](https://www.scintilla.org/SciTE.html)) doesn't rely on -- SciTE renders the buffer fine under 150% scaling:

![image](https://github.com/orbitalquark/textadept/assets/4930759/fc9e3347-fa1d-45f6-a5f2-2da6c54312c0)

**Comment by orbitalquark** [comment]
Correct. SciTE uses some native Windows rendering.
