### ISSUE TITLE
Request change of behaviour for rectangular selection to ignore line ends

### ISSUE THREAD

**Issue by chrisgeli** [orbitalquark/textadept#492]
Quite frequently, I'd like to remove/replace the ends of multiple lines, as in the following example where I want to keep the line starts but delete/replace everything past the capital letters:

```
keep me A delete me
keep me B I should go as well
keep me C don't need to keep this
keep me D delete!

```

My intuition (trained through years of using Notepad++) makes me hold down <kbd>Alt</kbd> while dragging the mouse from `A` to line `C`'s column where `this` (in the line above) ends.

Unfortunately, this doesn't work, I cannot select a block of line endings - unless the last of the lines is the longest of them all, in which case it works as I'd expect.  I don't like to have "virtual space" enabled either but thought it might help, which it didn't: The selection behaviour is still the same.

Any chance this could be changed such that whenever a rectangle is selected, the caret doesn't care about where the lines currently end?

**Comment by chrisgeli** [comment]
In addition to the above, I remembered that there's another use case for rectangular selections being able to start/end at any column number (including past line ends): Turning this
```
First line
Second longer line
Third short line
```
into that:

```
First line         -- new comment
Second longer line -- new comment
Third short line   -- new comment
```
Again, I'd simply <kbd>Alt</kbd>-drag vertically where I want the `--` to begin at a random column after `First line`, but am currently limited by its line length.

**Comment by orbitalquark** [comment]
I'm not aware of a Scintilla option that changes Alt+Click-and-drag behavior of creating rectangular selections to do what you describe :( I wonder what Notepad++ does...

**Comment by orbitalquark** [comment]
Fixed in https://github.com/orbitalquark/textadept/commit/6c0125c1b96f3740977d6eb45f8260f2d2d7c94f. I didn't realize the virtual space option was a bit field. Sorry about that :(

**Comment by chrisgeli** [comment]
I finally got around to testing this using the current nightly. Just in case someone wants to activate it the way I was used to from Notepad++, simply add the following line to the end of *~/.textadept/init.lua*:

`buffer.virtual_space_options = buffer.VS_RECTANGULARSELECTION`

Thanks for the feature!
