### ISSUE TITLE
Latest textadept crashes on Win7

### ISSUE THREAD

**Issue by brynne8** [orbitalquark/textadept#498]
The 12.0 alpha version works well on Win7, even 12.0 cannot run, because

```
无法定位程序输入点 CreateDXGIFactory2 与动态链接库 dxgi.dll
```
which translates to

```
Unable to locate program input point CreatDXGIFactory2 and dynamic link library dxgi.dll
```

**Comment by brynne8** [comment]
I found win7 is not supported in 12.0 beta. But win7 is still widely used.

**Comment by orbitalquark** [comment]
Sorry, Textadept depends on Qt (a GUI toolkit), which chooses its minimum supported system requirements. Unfortunately, Windows 7 is not among them :(

**Comment by M0JXD** [comment]
I know this is old but if you want to run Textadept on Windows 7 I've had success using this project: https://github.com/crystalidea/qt6windows7

I had to compile against the right version of Qt (6.8.3) and then swapped all the bundled DLLs for the ones on the the project's release page.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/eee1479d-b72e-4c8f-a0ed-95308f260d8b" />

Edit: I made a custom build for Textadept 13 that runs on Windows 7: https://github.com/M0JXD/textadept/releases/tag/13-alpha-win7
