### ISSUE TITLE
HTML files missing from docs in 12.2-Linux release

### ISSUE THREAD

**Issue by AndrewDDavis** [orbitalquark/textadept#500]
Similar to issue #240: 
The Linux release of v. 12.2 contains only markdown files rather than html in the docs directory (aside from index.html).

The `Show Manual` menu item is silently failing, and I'm assuming the missing html docs are the cause.

**Comment by orbitalquark** [comment]
Thanks for the report! This was a Linux only issue, should be fixed via https://github.com/orbitalquark/textadept/commit/0e63200eaa45d28c0d0678d71567b1c0605f4766, and should appear in the next nightly build.
