### ISSUE TITLE
When `~/.textadept/locale.conf` is present, **Edit** > **Preferences** followed by **Quick Open User Home** shows a single tab in the tab bar

### ISSUE THREAD

**Issue by georgeraraujo** [orbitalquark/textadept#503]
The behavior I describe below only happens when `~/.textadept/locale.conf` is present, i.e., when Textadept is localized. I am running the 16 Feb 2024 nightly on Windows 10.

I start Textadept. No file is open from the previous session.

![image](https://github.com/orbitalquark/textadept/assets/4930759/922ed3b7-bee6-48b6-8b4c-95e8b79ed5da)

I click on the **Edit** > **Preferences** menu item, and Textadept opens `~/.textadept/init.lua`.

![image](https://github.com/orbitalquark/textadept/assets/4930759/a6cfb501-759d-4563-a66b-665e98f2b793)

I click on the **Tools** > **Quick Open** > **Quickly Open User Home** menu item, open some other file in my `~/.textadept/` directory (namely, `~/.textadept/themes/base16-framer.lua`), and Textadept opens it. The tab bar appears and shows a single tab corresponding to the file I just opened, but there is no tab in the tab bar for `~/.textadept/init.lua` from the previous step.

![image](https://github.com/orbitalquark/textadept/assets/4930759/c50ba77f-e6f1-4086-b925-8f9a65f9f7e8)

I click on the **Buffer** > **Next Buffer** menu item, and the tab corresponding to `~/.textadept/init.lua` appears in the tab bar.

![image](https://github.com/orbitalquark/textadept/assets/4930759/85330df9-2f25-450b-a31b-45e31ba6949b)

The behavior does not happen when Textadept is not localized.

**Comment by orbitalquark** [comment]
Thanks for the report. I'll look into this when I have some time.

**Comment by orbitalquark** [comment]
I was not able to reproduce this erroneous behavior on any of the three platforms I tested on: Windows, macOS, and Linux.

I cannot see how the locale file would cause something like this, because Textadept just reads from it on startup to populate a table of localized strings/messages for display.

**Comment by georgeraraujo** [comment]
I just reproduced the issue with 12.3. When `~/.textadept/locale.conf` is present, the issue happens; when it is absent, the issue does not happen.

Feel free to close the issue. I only created it because I think it shouldn't go unreported.

**Comment by orbitalquark** [comment]
I still cannot reproduce this on any platform :( If you're still on Windows, do you mind trying to see if this still happens on a nightly build? It upgraded to Qt 6.7 from Qt 6.5. Maybe that had a beneficial effect.

**Comment by georgeraraujo** [comment]
I just tried the latest nightly, and the issue is gone! \o/

**Comment by orbitalquark** [comment]
Yay! I'm so happy to hear :)
