### ISSUE TITLE
Keypad / numpad's Enter sometimes doesn't behave like regular Enter/Return.

### ISSUE THREAD

**Issue by RamKromberg** [orbitalquark/textadept#504]
Apologizing in advance since the issue might not be a bug so much as a discussion topic / feature request... Still, I can't figure it out so here I go:

Keypad / numpad's Enter sometimes doesn't behave like regular Enter/Return. e.g. When doing Search & Replace, pressing Enter would trigger the Next action. However, pressing the numpad's Enter is ignored.

Now, since kpenter needs to do both newlines in the editor body and various confirmations/Next in different dialog boxes, I believe the best solution would be to have an option to bind kpenter(?) to Enter. However, I hadn't had much luck doing that.

Regards

**Comment by orbitalquark** [comment]
This was fixed in https://github.com/orbitalquark/textadept/commit/01eaec64fbb60ac2921c500b3e98aa028574dcc0 and is available in 12.3 beta and the nightlies. It will be available in the next stable release as well.
