### ISSUE TITLE
Autolinks in GitHub Flavored Markdown

### ISSUE THREAD

**Issue by lsoksane** [orbitalquark/textadept#51]
Rather than an issue, this is more of a feature request. GitHub Flavored Markdown is widely used, and the Markdown lexer doesn't understand autolinks, see <https://github.github.com/gfm/#autolinks> (in fact, this link was created using the autolink syntax). Adding autolinks would be great.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/553eb706c233d7088c4cb2bbd589cbf9eb0f1e72
