### ISSUE TITLE
Curses version opens with an error, session.lua:71 bad argument to iconv #2 (string expected, got nil)

### ISSUE THREAD

**Issue by quesada** [orbitalquark/textadept#510]
![image](https://github.com/orbitalquark/textadept/assets/182207/28febc2b-b8ec-48d2-9d70-b7f30239af03)

I don't think I have done anything at all with sessions. Well, the gui version was running, but not at the same time?

**Comment by orbitalquark** [comment]
It seems like Textadept is not properly detecting your filesystem's character encoding. First, it tries the `CHARSET` environment variable. If that does not work, then it tries `LC_ALL` followed by `LANG`. What are the values of those environment variables?

My system defines only `LANG`:

```
LANG=en_US.UTF-8
```

I wonder if it's worth falling back on `UTF-8` if all else fails.

**Comment by quesada** [comment]
I'm using fish. 
trined this on config.fish:

# for textadept to avoid errors
set CHARSET "UTF-8"
set LANG "en_US.UTF-8"

segfault persists
