### ISSUE TITLE
Curses version on mlterm seems to have a problem with soft wrapping

### ISSUE THREAD

**Issue by quesada** [orbitalquark/textadept#512]
Example:
![image](https://github.com/orbitalquark/textadept/assets/182207/f0a2ba7e-6f41-43a0-aab7-8b1405847003)

Mlterm on ubuntu 22.04, gnome, X11.

**Comment by orbitalquark** [comment]
Does this also happen in other terminals? I tried opening Textadept's README.md in a 40 character wide terminal (Konsole), and turned on wrap mode ("View: Toggle Wrap Mode" via Ctrl+P). Everything looks okay to me.

**Comment by quesada** [comment]
Yes, modern terminals like konsole do ok. It's mlterm that fails. You may wonder why choose mlterm. The answer is typing latency (5ms, whereas all modern terminals are above 40ms)

**Comment by orbitalquark** [comment]
Okay, then I don't think there's anything I can do about this. There's probably something different about how mlterm handles drawing/measuring/updating/etc., but I'm not versed enough in terminal emulation to know what.

**Comment by quesada** [comment]
Solved it by using a more modern terminal. Closing.
