### ISSUE TITLE
Configuring markdown and python language servers produces 'failed to execute language server'

### ISSUE THREAD

**Issue by quesada** [orbitalquark/textadept#515]
I wan to run language servers and replace kate and helix :)
But haven't been able to get it to work with the docs and examples in the TA module.

This is the config in kate:

`{
    "servers": {
        "markdown": {
            "command": ["zk", "lsp"],
            "root": ".zk"
        }
    },
        "python": {
            "command": ["python3", "-m", "pyls", "--check-parent-process"],
            "url": "https://github.com/palantir/python-language-server",
            "highlightingModeRegex": "^Python$"
        }
}
`

This is the config in helix (languages.toml

`[language-server.markdown]
command = "zk"
args = ["lsp"]
`

`[language-server.ltex]
command = "/home/q/.local/bin/ltex-ls"
`
`[language-server.ltex.config.ltex.dictionary]
"en-US" = ["Tp-Note","Zettelkasten"]
`
`# Python
[[language]]
name = "python"
language-servers = ["pylsp"]
roots = [".git"]
workspace-lsp-roots = ["src/updater"]
auto-format = true
`

`[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true, ignore = ["E501"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = false}
`

`# Markdown
[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown"]
roots = [".zk"]
`

`language-servers = [
  { name = "ltex"},
  { name = "markdown"},
]
`

This is my init.lua:
https://pastebin.com/edDv1cc6

Any examples that I can use in TA other than the ones in the documentation? Thanks!

**Comment by orbitalquark** [comment]
The only resource I know of is on the wiki: https://github.com/orbitalquark/textadept/wiki/LSP-Configurations
