### ISSUE TITLE
MacOS: Can't change preferences

### ISSUE THREAD

**Issue by rovf** [orbitalquark/textadept#519]
Running Textadapt on MacOS 12.7.3 exhibits the following strangeness:

In the "Textadept" menu, the menut entries for "Preferences" and "Quit Textadept" are greyed out.

While the hotkeys are accepted (for instance Command-Q indeed quits the editor), the key Command-, , which is the shortcut for the prefernces, opens an empty window for the file ~/.textadept/init.lua .  There are no settings which possibly could be edited.

**Comment by orbitalquark** [comment]
Thanks for the report about some menu items being disabled.

Settings are stored in *~/.textadept/init.lua*, which is empty by default: https://orbitalquark.github.io/textadept/manual.html#textadept

The various settings and options available are covered throughout the manual, as well as in the Lua API (https://orbitalquark.github.io/textadept/api.html). It can be a bit overwhelming to navigate, I admit, but for now that's probably the best resource available. Textadept's own *init.lua* file (https://github.com/orbitalquark/textadept/blob/262048734d92bf3bef61860b14b0561ef7f7fbba/init.lua#L75) has an organized list of buffer and view settings to help you get started.

**Comment by orbitalquark** [comment]
I've updated to Qt 6.7 on macOS (https://github.com/orbitalquark/textadept/commit/ffef0281e6d2ec8fcf6e802f903b489b20529fb1) and I'm not seeing the greyed out menu items anymore. Hopefully this will be fixed for you in tonight's nightly build.
