### ISSUE TITLE
Manual line breaks in LaTeX

### ISSUE THREAD

**Issue by lsoksane** [orbitalquark/textadept#52]
This is a very minor issue. The LaTeX lexer does not recognize `\\` in the right way, see <https://en.wikibooks.org/wiki/LaTeX/Paragraph_Formatting#Manual_breaks>. For example, in

    The Recipient
    \\1 Aaa St
    \\Bbb, Ccc

on last line `\Bbb` gets colored suggesting that it is a command.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scintillua/commit/90cfbe58d2b827834da48140ed408bcbcfd5ffbd
