### ISSUE TITLE
Cannot load built-in modules on macOS

### ISSUE THREAD

**Issue by achou11** [orbitalquark/textadept#525]
I was updating to the latest release of the app (12.4) and after doing the basic installation tasks, I noticed that I get the following warning when trying to open application:

<img width="280" alt="image" src="https://github.com/orbitalquark/textadept/assets/18542095/9457f906-069e-47de-9f33-92dac28bb351">

This happens when my init file requires any module that has a native `.so` file. I've only tested `file_diff` and `spellcheck` since I was following the example from https://orbitalquark.github.io/textadept/manual.html#installation.

I'm aware of the macOS "right-click" trick to bypass the warning, but not sure how that would work for these kinds of files since they're not really executables. I vaguely remember a CLI command that does the same thing but that seems tedious and not ideal when potentially working with several modules.

I can't remember if this was an issue before - I'm inclined to say that it wasn't but it's been a while since I last opened the app.

Reproduction steps:

1. Install Textadept and the extra modules (place the modules in  `$HOME/.textadept/modules/` directory)
2. Update `init.lua` with the following:

    ```lua
    require('file_diff')
    ```
3. Open Textadept

---

Textadept version: 12.4
OS: macOS 14.4.1 (Sonoma)

**Comment by orbitalquark** [comment]
Thanks for the report. macOS has been getting more and more overzealous with these types of things. I think you have to go into the security settings and click a button to bypass it, like you would when trying to run an application like Textadept from a "developer [that] cannot be verified". I should probably add a FAQ entry for this.

**Comment by achou11** [comment]
> I think you have to go into the security settings and click a button to bypass it

Ah yes this worked. Unforunate but not your fault 😄 Can close this.
