### ISSUE TITLE
how to make current line number have a different color?

### ISSUE THREAD

**Issue by YahYahDev** [orbitalquark/textadept#526]
so ive been looking through the docs and i cant seem to find what you would use to modify the line numbers in the editor any suggestions would be much appreciated!

ive tried reading through the following api docs

https://orbitalquark.github.io/textadept/api.html#configure-line-margins
https://orbitalquark.github.io/textadept/api.html#mark-lines-with-markers
https://orbitalquark.github.io/textadept/api.html#query-line-and-line-number-information

**Comment by rgieseke** [comment]
I think you need to adjust your theme file (e.g. a local copy of this file):

https://github.com/orbitalquark/textadept/blob/81180915559448f60101f1d3da61819b40591e83/themes/dark.lua#L34

**Comment by rgieseke** [comment]
Or do you mean changing the current line number only?

**Comment by YahYahDev** [comment]
i mean the current line only my bad for not specifiying

**Comment by orbitalquark** [comment]
Unfortunately, this is currently not supported by Scintilla (Textadept's editing component). For reference: https://groups.google.com/g/scintilla-interest/c/vPVto8c7tuo/m/_Ddln2Z0CAAJ

**Comment by YahYahDev** [comment]
Ok ty for checking/pointing me in the right direction!
