### ISSUE TITLE
Feature request: Expose linesAdded field of SCN_MODIFIED event

### ISSUE THREAD

**Issue by joshuakraemer** [orbitalquark/textadept#53]
Could you please consider exposing the `linesAdded` field of the `SCN_MODIFIED` event? I need the line count for my Elastic Tabstops module. At the moment, I need to calculate it again because of the missing field, see https://github.com/joshuakraemer/textadept-elastic-tabstops/blob/main/elastic_tabstops.lua#L143

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/textadept/commit/d52198ec5004edef17665b6ba4e5b0f0a7d12cd0. This should show up in the next nightly build.

Note that connecting to `events.MODIFIED` is still intentionally undocumented, so please be careful.

**Comment by joshuakraemer** [comment]
That's great, thank you very much!
