### ISSUE TITLE
Going for new style snippets, I can't makethem work as per documentation

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#535]
HI

last Textadept... I have been off for some time. Tryinh to port my snippets to 12.4 following the documentation about transforms:

Transforms

”${n:/upcase}”, “${n:/downcase}”, and “${n:/capitalize}” sequences, which represent the uppercase, lowercase, and capitalized forms, respectively, of the content of the nth capture. You can define your own transformation function in [textadept.snippets.transform_methods](https://orbitalquark.github.io/textadept/api.html#textadept.snippets.transform_methods).

However, these don't seem to work directly:

![image](https://github.com/orbitalquark/textadept/assets/3320432/884ece50-8400-474e-999d-9a7022a3f796)

Could the documentation be updated, please

Thanks a ton, /PA

**Comment by orbitalquark** [comment]
That section of the documentation is under the "Transforms" section. Your $3 placeholder is not a transform. Something like `${3/.+/${0:/upcase}/}` should work. There are a couple of test cases for transformations that you can reference:

- https://github.com/orbitalquark/textadept/blob/85f5b76521cf33aa1206b44473d7e3b38356dca9/test/test.lua#L3993
- https://github.com/orbitalquark/textadept/blob/85f5b76521cf33aa1206b44473d7e3b38356dca9/test/test.lua#L4202-L4208

Sorry for the trouble, but it looks like these types of snippets have won the snippet syntax war, so we have to go with it.

**Comment by paaguti** [comment]
OK, but my point is that the doc is somehow misleading ;-) 

Maybe if you highlight the following `They have the following syntax: “${n/regex/format/options}”. ` it would be enough. Currently is is quite hidden in the paragraph and it doesn't look as important as the list below, where you have things that look like mirrors etc.
