### ISSUE TITLE
How to change window size and maximize it from init.lua?

### ISSUE THREAD

**Issue by winterwolf** [orbitalquark/textadept#54]
I am not satisfied with the default window size and changing the **ui.size** values does nothing.
In theory, I could solve this issue by calling wmctrl through os.execute but I don't like such a crutch.
There should be some native solution...

**Comment by orbitalquark** [comment]
Textadept stores window geometry and maximized state in a session file, which is loaded after your *~/.textadept/init.lua* is read, so that's probably what's undoing your settings. Try wrapping your settings in an `events.INITIALIZED` handler:

    events.connect(events.INITIALIZED, function()
      ui.maximized = true
    end)
