### ISSUE TITLE
lfs.walk() hangs when passed a non-existent directory path.

### ISSUE THREAD

**Issue by jxzwp** [orbitalquark/textadept#543]
Running the following code will cause Textadept to hang, but only when the directory path passed to `lfs.walk()`   is non-existent.
```lua
local dir = '/some/non-existent/directory/'
for p in lfs.walk(dir) do 
    print(p)
end
```

The problem is in `walk()` in lfs_ext.lua at the line below. `lfs.dir(dir)` raises an error when the `dir` doesn't exist, but the error isn't caught, which causes the hang. Using `pcall()` or doing a pre-check to make sure the directory exists should resolve the issue.  

https://github.com/orbitalquark/textadept/blob/3fe3ad4836c469c2a30233a244bb297659d8f672/core/lfs_ext.lua#L29

Thanks for all the time you've spent developing Textadept.

**Comment by orbitalquark** [comment]
Thanks for the detailed report and analysis! This should be fixed in https://github.com/orbitalquark/textadept/commit/5a08d9dca99d69536925fb7f0fee977d3bf21583
