### ISSUE TITLE
Building nightly failed on target `termkey-populate`

### ISSUE THREAD

**Issue by paaguti** [orbitalquark/textadept#549]
```
CMake Error at termkey-subbuild/termkey-populate-prefix/src/termkey-populate-stamp/download-termkey-populate.cmake:170 (message):
  Each download failed!

    error: downloading 'https://www.leonerd.org.uk/code/libtermkey/libtermkey-0.22.tar.gz' failed
          status_code: 28
          status_string: "Timeout was reached"
          log:
          --- LOG BEGIN ---
            Trying 188.166.172.189:443...

  Connected to www.leonerd.org.uk (188.166.172.189) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  TLSv1.0 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  SSL connection timeout

  Closing connection 0

  

          --- LOG END ---
          
    
```
Site seems to be down.

There seems to be a copy in https://github.com/neovim/libtermkey/archive/refs/tags/v0.22.tar.gz

**Comment by paaguti** [comment]
Confirmed that TA can be built with the archived termkey github

**Comment by orbitalquark** [comment]
Textadept has its own copy in the https://github.com/orbitalquark/textadept-build project.

**Comment by paaguti** [comment]
Fine, then why is the original used in CMake ? ;-)

**Comment by orbitalquark** [comment]
Many users prefer pulling from the actual source when compiling 
themselves. Textadept builds from cached sources on GitHub to avoid 
temporary network issues, and also to avoid repeatedly requesting 
downloads from external servers for nightly builds.
