### ISSUE TITLE
open normal html file and it gives error

### ISSUE THREAD

**Issue by Mayur-hot** [orbitalquark/textadept#556]
![2](https://github.com/user-attachments/assets/206bb0ae-f241-4d9f-adef-bb5484295ee8)

**Comment by Mayur-hot** [comment]
If I change .html to no extention, then file opens without any error...

so its regarding .html problem, and its actually html file also.

**Comment by Mayur-hot** [comment]
[html.log](https://github.com/user-attachments/files/16505226/html.log)

just rename html.log to html file and try to open in textadept... you will get error.

**Comment by orbitalquark** [comment]
Thanks for the file. I see that there is an issue, and will look into fixing it when I have some time.

**Comment by orbitalquark** [comment]
I've pushed a fix for this file in https://github.com/orbitalquark/scintillua/commit/f1375d323c19c6264c3ad56abb1c24f52f3a28b9, and it should show up in tonight's nightly build.

If you run into this again, you can set `lpeg.setmaxstack()` in your *~/.textadept/init.lua* as a workaround. For example:

```
lpeg.setmaxstack(2048)
```

It is not clear to me how large this value should be. Your file needs a value of 1329 to work.

**Comment by Mayur-hot** [comment]
Thank You, one more Bug....

create a new blank text file.. and save it..
so not possible to save a file with 0 data...

it adds two blank lines
1
2

so, empty file save = 1 byte.., expected 0 byte

but using other editor I can able to save empty file with 0 byte.

**Comment by orbitalquark** [comment]
You'll want to turn off `io.ensure_final_newline` (https://orbitalquark.github.io/textadept/api.html#io.ensure_final_newline)
