### ISSUE TITLE
Buggy text in terminal version when maximizing

### ISSUE THREAD

**Issue by luizfernandonb** [orbitalquark/textadept#560]
When I open a file in the terminal version and maximize the terminal version, the text in the file becomes buggy

![image](https://github.com/user-attachments/assets/41938f5f-7543-449c-ab16-03456e5cd152)

**Comment by orbitalquark** [comment]
Unfortunately, I don't think the Windows console notifies applications that the window size has changed. You will have to quit Textadept and restart it to use the new size.

**Comment by luizfernandonb** [comment]
Ok, thanks
