### ISSUE TITLE
Build error with Scintilla curses patch

### ISSUE THREAD

**Issue by rgieseke** [orbitalquark/textadept#57]
With a clean checkout i get an error while running `make deps`

```
unzip -d scintilla/curses 6a774158d8a3c7bc7ea120bc01cdb016fa351a7e.zip && mv scintilla/curses/*/* scintilla/curses
Archive:  6a774158d8a3c7bc7ea120bc01cdb016fa351a7e.zip
6a774158d8a3c7bc7ea120bc01cdb016fa351a7e
   creating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/.hgtags  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/LICENSE  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/Makefile  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/README.md  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/ScintillaCurses.cxx  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/ScintillaCurses.h  
   creating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/
   creating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/_layouts/
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/_layouts/default.html  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/api.md  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/changelog.md  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/fill_layout.lua  
   creating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/images/
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/images/scinterm.png  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/index.md  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/markdowndoc.lua  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/scinterm.luadoc  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/style.css  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/docs/thanks.md  
   creating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/jinx/
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/jinx/Makefile  
  inflating: scintilla/curses/scinterm-6a774158d8a3c7bc7ea120bc01cdb016fa351a7e/jinx/jinx.c  
make -C scintilla/curses patch
make[1]: Entering directory '/home/robert/.local/bin/textadept/src/scintilla/curses'
make[1]: *** No rule to make target 'patch'.  Stop.
make[1]: Leaving directory '/home/robert/.local/bin/textadept/src/scintilla/curses'
make: *** [Makefile:415: scintilla/curses] Error 2
```

**Comment by rgieseke** [comment]
Got it, fixed it with `make NIGHTLY=1`

**Comment by rgieseke** [comment]
`make curses` still errors with
```
g++ -c -Os -std=c++17 -pedantic -DCURSES -DSCI_LEXER -DSCI_EMPTYCATALOGUE -DNDEBUG -Iscintilla/include -Iscintilla/src -Iscintilla/lexlib -Wall -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 scintilla/curses/ScintillaCurses.cxx -o ScintillaCurses.o
scintilla/curses/ScintillaCurses.cxx: In constructor ‘ScintillaCurses::ScintillaCurses(void (*)(void*, int, SCNotification*, void*), void*)’:
scintilla/curses/ScintillaCurses.cxx:973:31: error: invalid conversion from ‘void (*)(Scintilla::Surface*, Scintilla::PRectangle, int, const Scintilla::ViewStyle&)’ to ‘Scintilla::DrawTabArrowFn’ {aka ‘void (*)(Scintilla::Surface*, Scintilla::PRectangle, int)’} [-fpermissive]
  973 |     view.customDrawTabArrow = DrawTabArrow; // draw text arrows for tabs
      |                               ^~~~~~~~~~~~
      |                               |
      |                               void (*)(Scintilla::Surface*, Scintilla::PRectangle, int, const Scintilla::ViewStyle&)
make: *** [Makefile:186: ScintillaCurses.o] Error 1
```

**Comment by orbitalquark** [comment]
Try deleting the *src/scintilla/curses/* directory and running `make deps NIGHTLY=1` again. It doesn't look like the necessary Scintilla patches were made. The output should look something like this:

    unzip -d scintilla/curses 6a774158d8a3c7bc7ea120bc01cdb016fa351a7e.zip && mv scintilla/curses/*/* scintilla/curses
    Archive:  6a774158d8a3c7bc7ea120bc01cdb016fa351a7e.zip
    e642eca051a438b5377e980ebb91ec2e1a918687
      creating: scintilla/curses/scinterm-default/
      inflating: scintilla/curses/scinterm-default/.hgtags  
      inflating: scintilla/curses/scinterm-default/LICENSE  
      inflating: scintilla/curses/scinterm-default/Makefile  
      inflating: scintilla/curses/scinterm-default/README.md  
      inflating: scintilla/curses/scinterm-default/ScintillaCurses.cxx  
      inflating: scintilla/curses/scinterm-default/ScintillaCurses.h  
       creating: scintilla/curses/scinterm-default/docs/
       creating: scintilla/curses/scinterm-default/docs/_layouts/
      inflating: scintilla/curses/scinterm-default/docs/_layouts/default.html  
      inflating: scintilla/curses/scinterm-default/docs/api.md  
      inflating: scintilla/curses/scinterm-default/docs/changelog.md  
      inflating: scintilla/curses/scinterm-default/docs/fill_layout.lua  
       creating: scintilla/curses/scinterm-default/docs/images/
      inflating: scintilla/curses/scinterm-default/docs/images/scinterm.png  
      inflating: scintilla/curses/scinterm-default/docs/index.md  
      inflating: scintilla/curses/scinterm-default/docs/markdowndoc.lua  
      inflating: scintilla/curses/scinterm-default/docs/scinterm.luadoc  
      inflating: scintilla/curses/scinterm-default/docs/style.css  
      inflating: scintilla/curses/scinterm-default/docs/thanks.md  
       creating: scintilla/curses/scinterm-default/jinx/
      inflating: scintilla/curses/scinterm-default/jinx/Makefile  
      inflating: scintilla/curses/scinterm-default/jinx/jinx.c  
       creating: scintilla/curses/scinterm-default/patches/
      inflating: scintilla/curses/scinterm-default/patches/01-drawtabarrow.patch  
      inflating: scintilla/curses/scinterm-default/patches/02-caretstyle_curses.patch  
    make -C scintilla/curses patch
    make[2]: Entering directory '/__w/textadept/textadept/src/scintilla/curses'
    Applying patches/02-caretstyle_curses.patch
    patching file doc/ScintillaDoc.html
    Hunk #1 succeeded at 3314 (offset 10 lines).
    patching file include/Scintilla.h
    patching file src/EditView.cxx
    patching file src/Editor.cxx
    patching file src/PositionCache.cxx
    patching file src/ViewStyle.cxx
    patching file src/ViewStyle.h
    Applying patches/01-drawtabarrow.patch
    patching file src/EditView.cxx
    Hunk #1 succeeded at 1972 (offset 21 lines).
    patching file src/EditView.h
    make[2]: Leaving directory '/__w/textadept/textadept/src/scintilla/curses'

After those patches are applied, `make` should build everything without a problem.

**Comment by rgieseke** [comment]
Thanks! With a clean restart i got it to compile.
