### ISSUE TITLE
Suggestion for Find & Replace

### ISSUE THREAD

**Issue by Mayur-hot** [orbitalquark/textadept#570]
![Screenshot_2024-09-16_19-46-27](https://github.com/user-attachments/assets/bb9c3a85-0f86-4473-9f3b-a66f9cd403a3)

Just Compare above image's Find & Replace Panel with Current TextAdepta to get Diff.
Wants to add two find & Replace options...

1) Backslash  (user can find hidden char like \n \t \r etc.... + also replace it..
2) Highlight  (I know by default editor is just replace in selection only, but one more option for balanced gui.. (may be useless)

Thank you Sir.

**Comment by Mayur-hot** [comment]
if possible for find and replace.. 

need to store last search key..  + last replace key... if possible, so even after closing.. then opening editor automatically load last search.. & Replace..

**Comment by orbitalquark** [comment]
1. The existing "Regex" option enables searching and replacing for \n, \t, and friends.
2. Set `ui.find.highlight_all_matches = true` in your *~/.textadept/init.lua*. (https://orbitalquark.github.io/textadept/api.html#ui.find.highlight_all_matches)

You can also use your *~/.textadept/init.lua* to connect to `events.SESSION_SAVE` and `events.SESSION_LOAD` for saving and restoring find/replace entries. Something like this:

```
events.connect(events.SESSION_SAVE, function(session)
  session.find = {find_text = ui.find.find_entry_text, replace_text = ui.find.replace_entry_text}
end)

events.connect(events.SESSION_LOAD, function(session)
  if not session.find then return end
  ui.find.find_entry_text = session.find.find_text
  ui.find.replace_entry_text = session.find.replace_text
end)
```

(I did not test this, but that's the idea.)

**Comment by Mayur-hot** [comment]
> 1. The existing "Regex" option enables searching and replacing for \n, \t, and friends.
> 2. Set `ui.find.highlight_all_matches = true` in your _~/.textadept/init.lua_. (https://orbitalquark.github.io/textadept/api.html#ui.find.highlight_all_matches)
> 
> You can also use your _~/.textadept/init.lua_ to connect to `events.SESSION_SAVE` and `events.SESSION_LOAD` for saving and restoring find/replace entries. Something like this:
> 
> ```
> events.connect(events.SESSION_SAVE, function(session)
>   session.find = {find_text = ui.find.find_entry_text, replace_text = ui.find.replace_entry_text}
> end)
> 
> events.connect(events.SESSION_LOAD, function(session)
>   if not session.find then return end
>   ui.find.find_entry_text = session.find.find_text
>   ui.find.replace_entry_text = session.find.replace_text
> end)
> ```
> 
> (I did not test this, but that's the idea.)

Thanks for Reply...
`ui.find.highlight_all_matches = true`

above is the solution, but by default its false....
so adding one more option in find/replace panel help a lot.. user can enable or disable it based on need..
some time user have to just replace normal "\n", then default find and replace works well.. but some time
user wants to replace actual new line char... means not "\n" but actual LF..
then one more option help a normal user lot...

So, `ui.find.highlight_all_matches = false` or `ui.find.highlight_all_matches = true`

Both are needed based on needs..
Thanks You Boss.

**Comment by Mayur-hot** [comment]
local function find(text, next, flags, no_wrap, wrapped)
  if M.backslash1 then
    text = text:gsub( '\\n', '\n'):gsub( '\\t', '\t'):gsub( '\\r', '\r'):gsub( '\\r\\n', '\r\n')
  end
  
in textadept modules find.lua.. I added above code to replace \n \t \r \r\n when user choose M.backslash1
also for replace..

events.connect(events.REPLACE_ALL, function(ftext, rtext)
  if M.backslash1 then
    ftext = ftext:gsub( '\\n', '\n'):gsub( '\\t', '\t'):gsub( '\\r', '\r'):gsub( '\\r\\n', '\r\n')
  end
