### ISSUE TITLE
Column width does not handle tabs correctly

### ISSUE THREAD

**Issue by d4v3y5c0n3s** [orbitalquark/textadept#574]
I ran into an issue where I noticed that the column number of the error messages from a compiler I was using didn't match up with the column number that Textadept showed me.

After fiddling around, I discovered that Textadept counts a tab as 8 columns wide.

This is a problem because compilers (in my experience) treat a tab as 1 character when describing the column number of an error message.

Let me know if you'd like more information on the problem or have any questions, and I'll do my best to respond quickly.

(I'm using Textadept 12.4 on Windows 11)

**Comment by orbitalquark** [comment]
Thanks for the report. This should be fixed in https://github.com/orbitalquark/textadept/commit/bcd96c8a2528a7d8edac25effbecc9425d813e12. Until 12.5 is released, you can make that change manually to your Textadept's *modules/textadept/run.lua* file.

**Comment by d4v3y5c0n3s** [comment]
Thank you, I appreciate the quick response! 😄 

As a side note, I use Textadept as my daily driver text editor, and I like it a lot.  I've previously used a bunch of text editors from VSCode to Emacs, but Textadept strikes a balance of being lightweight, feature-filled, and highly customizable that I couldn't find in other editors.  So I just wanted to say, thank you for making Textadept! 😎

**Comment by orbitalquark** [comment]
Thanks for your kind words! I appreciate the feedback very much :)
