### ISSUE TITLE
File Browser Module "Open Directory..." menu does not work.

### ISSUE THREAD

**Issue by M0JXD** [orbitalquark/textadept#578]
The menu entry for the [file browser](https://github.com/orbitalquark/textadept/wiki/ta-filebrowser) module doesn't work, it tries to open files instead. This is due to an API change since Textadept 11.5.

The fix (on line 71) is to change "select_only_directories" to "only_dirs" like so:

```
function M.init(dir, filter)
  dir = dir or ui.dialogs.open{
    title = 'Open Directory', only_dirs = true
  }
  ...
```

Because files in the wiki can't be edited in the online editor I tried to contribute by cloning the wiki and pushing back but I keep getting authentication errors, so I thought I'd report it here :)

Thanks

**Comment by orbitalquark** [comment]
Thank you! I've updated the wiki. Sorry to hear about your troubles attempting to update it yourself :(
