### ISSUE TITLE
Rearranging the tab bar does not work in the GTK version.

### ISSUE THREAD

**Issue by M0JXD** [orbitalquark/textadept#579]
I'm on Linux, it works in the Qt version.

Thanks.

**Comment by orbitalquark** [comment]
That's odd. It works for me in Textadept 12.5 in my Ubuntu 24.04 VM. It used to be the case that you had to click and drag using the [tops of tabs][1] (or anywhere outside the tab label). Maybe it's still the case for the version you are using?

[1]: https://github.com/orbitalquark/textadept/blob/6635df2e3e383e61d6303b7056fb739cc44391b4/docs/manual.md?plain=1#L397

**Comment by orbitalquark** [comment]
For whatever reason, you have to click and drag anywhere in the tab outside the label (bottom, top, or edges). GTK tabs with a label widget inside will not allow clicking and dragging. I don't know how to work around this. Sorry about that :( This was yet another reason for switching to Qt from GTK...

**Comment by M0JXD** [comment]
Oh right, I see! It works that way, I kept clicking the label without realising.

Since installing qt5ct I can theme the Qt one to look nearly exactly the same GTK one does in my DE so it's not really a problem :)

I can't seem to do this for Qt6 applications yet though. I've seen a lot of apps switching from GTK to Qt.

Regarding a fix, might be worth having a look at [Xed](https://github.com/linuxmint/xed/blob/master/xed/xed-tab.c) as their tabs seem to work, although their implementation might be incompatible with Textadept.

Thanks for your help!

Edit: Thanks to [qt6gtk2](https://github.com/trialuser02/qt6gtk2) I can theme Qt6 apps too :)
