### ISSUE TITLE
Underscore character is not visible

### ISSUE THREAD

**Issue by jpork** [orbitalquark/textadept#67]
All underscore characters are invisible in textadept-11.1. 

There is an Scintilla issue [#2173 SciTE do not show the underscore with gtk-3.24.18 ](https://sourceforge.net/p/scintilla/bugs/2173/) which claims to be fixed for version 4.4.0.

According to textadepts release notes it contains sintilla-4.4.5 since version 11.0 beta.

But still I cannot see any underscore.

I run textadept-11.1 on fedora:

    > hostnamectl
      Operating System: Fedora 33 (Workstation Edition)
      CPE OS Name: cpe:/o:fedoraproject:fedora:33
      Kernel: Linux 5.10.19-200.fc33.x86_64
      Architecture: x86-64
  
    > gnome-shell --version
      GNOME Shell 3.38.3
  
    > dnf list 'gtk*'
      Installed Packages
      gtk-update-icon-cache.x86_64    3.24.26-1.fc33 
      gtk-vnc2.x86_64                 1.0.0-3.fc33   
      gtk2.x86_64                     2.24.33-1.fc33 
      gtk3.x86_64                     3.24.26-1.fc33 
      gtkd.x86_64                     3.9.0-3.fc33   
      gtkmm30.x86_64                  3.24.3-1.fc33  
      gtksourceview3.x86_64           3.24.11-4.fc33 
      gtksourceview4.x86_64           4.8.0-1.fc33

**Comment by jpork** [comment]
I've just observed that the visibility of the underscore depends on the zoom size. 

When zoom-in the editors content in steps the underscores become in some steps visible in other steps they are invisible.

**Comment by orbitalquark** [comment]
According to the SciTE ticket you linked, the "potential fix [...] may not solve every case but it should help in most." Unfortunately it looks like you are not in the "most" category. Try putting this in your *~/.textadept/init.lua*:

  view.extra_descent = 1

**Comment by jpork** [comment]
Cool this solves my problem.
Thanks
