### ISSUE TITLE
Indent between slider and edge of window in GTK

### ISSUE THREAD

**Issue by winterwolf** [orbitalquark/textadept#68]
Forgive me for finding fault with such trifles, but they annoy me the most. There is the indent 1 or 2 pixels which makes me aim exactly at the slider, and if I just move the cursor to the edge of the screen (when window is maximized), the slider don't react or flies away in a random direction.

![Peek 2021-03-05 14-11](https://user-images.githubusercontent.com/42620439/110116351-0cfc8280-7dc0-11eb-8170-26cd96363437.gif)

**Comment by orbitalquark** [comment]
Sadly, this is a GTK issue that I cannot do anything about. (GTK is the GUI toolkit Textadept uses.) You can try using a different GTK theme to solve this issue. Your Linux distribution should provide a tool that allows you to change said theme.

**Comment by winterwolf** [comment]
> Sadly, this is a GTK issue that I cannot do anything about. (GTK is the GUI toolkit Textadept uses.) You can try using a different GTK theme to solve this issue. Your Linux distribution should provide a tool that allows you to change said theme.

@orbitalquark  you're right, this is GTK issue, but it happens only with Textadept. It doesn't happens with any other GTK application and my current theme doesn't have any gaps on window borders.

**Comment by orbitalquark** [comment]
Are the other applications you're comparing with GTK2 or GTK3 applications? Textadept is provided as a GTK2 application. You can compile it for GTK3, so if it's a GTK2-specific issue, then you can workaround your issue by compiling Textadept manually for GTK3.

**Comment by winterwolf** [comment]
@orbitalquark To be honest, I just tried to create my own GTK application and it has the same problem. But for some reason, other applications, such as Firefox, Synaptic, Evince and many others, do not have this problem.

**Comment by winterwolf** [comment]
@orbitalquark Evince and Firefox are gtk3, but Synaptic is gtk2 based.
