### ISSUE TITLE
Prefer XDG Directories

### ISSUE THREAD

**Issue by BenWestcott** [orbitalquark/textadept#69]
Currently, on linux, textadept drops its configuration in `/home/user/.textadept`, even when the `XDG_CONFIG_HOME` environment variable is set (usually to `/home/user/.config`). It would be more polite to place them in and read them from the standards-defined config folder when possible, instead of cluttering the home folder. Of course, a fallback would be needed to not break existing user's configs.

**Comment by orbitalquark** [comment]
Thanks for the suggestion. This is probably an unpopular opinion, but I prefer one config directory for all platforms, especially since I use Textadept on both Windows and Linux. I like being able to go to *~/.textadept*, refer to that directory when providing support, and have the documentation refer to it as well. You can always set an alias/script to invoke Textadept with `-u $XDG_CONFIG_HOME/textadept` arguments.

**Comment by TheJuiceFR** [comment]
> You can always set an alias/script to invoke Textadept with `-u $XDG_CONFIG_HOME/textadept` arguments.

Currently; when I try to open Textadept with rofi (program launcher) or nemo (file manager) they don't account for environment variables. I've tried adding aliases in the following files:
~/.bashrc
~/.bashprofile
~/.xprofile
/etc/environment
/etc/profile.d/textadept.sh

None seem to create a system-wide alias.

The only solution I see at this point is to replace /bin/textadept with a script that runs Textadept with the desired arguments; but this would likely be broken as soon as I update Textadept.

All this to say, you've stated the solution very plainly and simply, when the solution is clearly not plain or simple to me.

**Comment by orbitalquark** [comment]
Yes, I would advocate using a global 'textadept' script that would invoke your Textadept with the proper environment variables. I don't understand how it would be broken as soon as you update, provide you just put an updated version of Textadept in the same location. Do you mind elaborating further on your concern here? Sorry for the inconvenience :(

**Comment by TheJuiceFR** [comment]
Excuse my inexperience, but I installed Textadept using the Arch user repository. This automatically created a symbolic link at /bin/textadept, and I assume that this link is destroyed and remade whenever the software is updated.

I've discovered that I can edit textadept/core/args.lua to achieve the desired functionality, but this solution faces the same issue.

**Comment by orbitalquark** [comment]
So then perhaps use a directory in `$PATH` that comes before */bin/textadept* where you could place your custom launcher? On my system, `$PATH` contains:

    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

If my package manager created */usr/bin/textadept*, then I could create */usr/local/bin/textadept* that invokes */usr/bin/textadept* with custom arguments, and that file would not be overwritten on update.

If you don't want to do something that requires elevated privileges, you could add a local directory to $PATH and put your launcher there. For example, my *~/.profile* file contains:

    PATH="$HOME/bin:$PATH"

I could create *~/bin/textadept* that invokes */usr/bin/textadept* with custom arguments. After you log out and log back in again, all applications (including your file managers) should respect your new `$PATH`.

Hopefully one of those options works for you.

**Comment by TheJuiceFR** [comment]
I think I've got a satisfying solution; thanks.

For anyone reading in the future; create a file /usr/local/bin/textadept with the contents:
>#!/bin/bash
>
>/usr/bin/textadept -u ~/.config/textadept "$@"

Then run `sudo chmod 755 /usr/local/bin/textadept` to change the file to the correct permissions.
