### ISSUE TITLE
How to change fold style?

### ISSUE THREAD

**Issue by ghost** [orbitalquark/textadept#70]
I've grepped through all docs and source code and I cannot find how to change fold style to "arrow"? Is it no longer possible to tweak folding style?

**Comment by orbitalquark** [comment]
https://github.com/orbitalquark/textadept/blob/46c257bc5ffc80d0b0ebee522af11a118a60d323/init.lua#L218

Just put those uncommented lines in your *~/.textadept/init.lua*.

**Comment by ghost** [comment]
:facepalm: Apparently my "grepping" skills failed me in this instance. Embarrassed. Thanks @orbitalquark!
