### ISSUE TITLE
Textadept don't see libraries from luarocks

### ISSUE THREAD

**Issue by lua-rocks** [orbitalquark/textadept#87]
I have 2 versions of lua installed: luajit and lua5.3.
Here is output from luarocks for both versions:

**> luarocks**
```
Configuration:
   Lua:
      Version    : 5.1
      Interpreter: /usr/bin/luajit (ok)
      LUA_DIR    : /usr (ok)
      LUA_BINDIR : /usr/bin (ok)
      LUA_INCDIR : /usr/local/include (ok)
      LUA_LIBDIR : /usr/lib/x86_64-linux-gnu (ok)

   Configuration files:
      System  : /usr/local/etc/luarocks/config-5.1.lua (ok)
      User    : /home/luarocks/.luarocks/config-5.1.lua (ok)

   Rocks trees in use:
      /home/luarocks/.luarocks ("user")
      /usr/local ("system")
```
**> luarocks --lua-version=5.3**
```
Configuration:
   Lua:
      Version    : 5.3
      Interpreter: /usr/bin/lua5.3 (ok)
      LUA_DIR    : /usr (ok)
      LUA_BINDIR : /usr/bin (ok)
      LUA_INCDIR : /usr/include/lua5.3 (ok)
      LUA_LIBDIR : /usr/lib/x86_64-linux-gnu (ok)

   Configuration files:
      System  : /usr/local/etc/luarocks/config-5.3.lua (ok)
      User    : /home/luarocks/.luarocks/config-5.3.lua (ok)

   Rocks trees in use:
      /home/luarocks/.luarocks ("user")
      /usr/local ("system")
```

As far as I know, textadept uses lua5.3, but when I install rock like this:
```
sudo luarocks --lua-version=5.3 install dkjson
```
Textadept doesn't see it, but lua5.3 interpreter does.

**Comment by rgieseke** [comment]
It should work when you add the Luarocks path to Textadept's `package.path` variable (and/or `package.cpath`).
You could also define a separate rock path just for Textadept. 

Only problem could be if there were relevant differences between Lua 5.3 and Lua 5.4 for your packages (as latest Textadept uses 5.4).

**Comment by rgieseke** [comment]
The current default definition is here, in `init.lua`: https://github.com/orbitalquark/textadept/blob/3d69ae01c0f2421a89b862ec5fea635a40826896/init.lua

**Comment by lua-rocks** [comment]
@rgieseke thank you! I just copy-pasted paths from interpreter to init.lua and now it seems works fine:
```
package.path = package.path .. ';/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;./?.lua;./?/init.lua'

package.cpath = package.cpath .. ';/usr/local/lib/lua/5.3/?.so;/usr/lib/x86_64-linux-gnu/lua/5.3/?.so;/usr/lib/lua/5.3/?.so;/usr/local/lib/lua/5.3/loadall.so;./?.so'
```
But I don't understand why these paths are not included by default.

**Comment by rgieseke** [comment]
> But I don't understand why these paths are not included by default.

They are likely not standardized between the different Linuxes, BSDs and macOS ... (and 5.3 or 5.4).
Also it would make it even harder to debug other people's Textadept config problems i guess ... (Textadept ships with Lpeg for example but it could also be installed from Luarocks, you installed dkjson but it might also be part of a Textadept module ...)

**Comment by lua-rocks** [comment]
Ok, I got it. Thank you very much!
